objects/Bulk_Upload_Donations__c.object
<CustomObject>
    <fields>
        <fullName>Donation_Count__c</fullName>
        <label>Donation Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Error_Reason__c</fullName>
        <label>Error Reason</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Success</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>In Progress</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_Donation_Amount__c</fullName>
        <label>Total Donation Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Rows__c</fullName>
        <label>Total Rows</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Upload_File_Type__c</fullName>
        <label>Upload File Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bulk Upload Donations</label>
    <nameField>
        <label>Bulk Upload Donations Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bulk Upload Donations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BulkUploadController.cls
/**
 * @description       : 
 * @author            : Iamsfdeveloper
 * @group             : 
 * @last modified on  : 06-11-2021
 * @last modified by  : Iamsfdeveloper
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   06-11-2021   Iamsfdeveloper   Initial Version
**/
public without sharing class BulkUploadController {
    @AuraEnabled
    public Static  List<Bulk_Upload_Donations__c> insertDonationsFromCSVFile(String dataFromSpreadsheet,string uploadType,String fileName){
        List<Bulk_Upload_Donations__c> insertedDonationList = new List<Bulk_Upload_Donations__c>();
		insertedDonationList = [Select Id from Bulk_Upload_Donations__c where Name=:fileName];
            If(insertedDonationList.size() > 0){
                return insertedDonationList;
            }
            system.debug('dataFromSpreadsheet'+dataFromSpreadsheet);
            Bulk_Upload_Donations__c inserFileDetails = new Bulk_Upload_Donations__c ();
            inserFileDetails.Name  = fileName;
            inserFileDetails.Upload_File_Type__c  = uploadType;
            inserFileDetails.Status__c = 'In Progress';
            insert inserFileDetails;
            Attachment a = new Attachment(Body=Blob.valueOf(dataFromSpreadsheet),parentId=inserFileDetails.Id,Name=fileName);
            insert a;
            BulkUploadProcessFuture bupf = new BulkUploadProcessFuture(inserFileDetails.Id,uploadType,dataFromSpreadsheet,false)  ;
            Database.executebatch(bupf, 25);
        	insertedDonationList = [Select Id,Name,Upload_File_Type__c,Status__c,Total_Rows__c,Donation_Count__c,Total_Donation_Amount__c,Error_Reason__c,CreatedDate  From Bulk_Upload_Donations__c where createdbyid=:userinfo.getuserid() limit 20];
    		return insertedDonationList;         

    }
    
    @AuraEnabled
    public Static List<Bulk_Upload_Donations__c> initGetData(){
        Id recId;
        List<Bulk_Upload_Donations__c> processList = [Select Id,Name,Upload_File_Type__c,Status__c,Total_Rows__c,Donation_Count__c,Total_Donation_Amount__c,Error_Reason__c,CreatedDate  From Bulk_Upload_Donations__c where createdbyid=:userinfo.getuserid() limit 20];
        return processList;
    }           
    
}