objects/Call_List__c.object
<CustomObject>
    <fields>
        <fullName>CampaignId__c</fullName>
        <label>CampaignId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CampaignMemberId__c</fullName>
        <label>CampaignMemberId</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactId__c</fullName>
        <label>ContactId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Queue_Name__c</fullName>
        <label>Queue_Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Call List</label>
    <nameField>
        <label>Donor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/CreateCallList_For_CampaignMember.cls
/**
 * @description       : 
 * @author            : Iamsfdeveloper
 * @group             : 
 * @last modified on  : 02-08-2021
 * @last modified by  : Iamsfdeveloper
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   02-08-2021   Iamsfdeveloper   Initial Version
**/
global class CreateCallList_For_CampaignMember {
    global static void createCallList(List<CampaignMember> newList){
        list<Call_List__c> callListToInsert = new List<Call_List__c>();

        for(CampaignMember cm : newList){
            System.debug('cm.Contact_Type__c=====> '+cm.Contact_Type__c);
            if(cm.contactId !=null && cm.Campaign_Type__c =='Outbound_Calling' && cm.Contact_Type__c !='Orphan'){
                string Name = (cm.FirstName != null)? cm.FirstName+' '+cm.LastName:cm.LastName;
                callListToInsert.add(new Call_list__c(Name=Name,ContactId__c=cm.contactId,CampaignMemberId__c = cm.Id, CampaignId__c=cm.CampaignId, Queue_Name__c=cm.Queue_Name__c)); 
            }
        }
        if(callListToInsert.size()>0){
            insert callListToInsert;
        }
    }
}