objects/Call_List__c.object
<CustomObject>
    <fields>
        <fullName>CampaignId__c</fullName>
        <label>CampaignId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Call List</label>
    <nameField>
        <label>Donor Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Call List</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Campaign_Product_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Product Allocations</relationshipLabel>
        <relationshipName>Campaign_Product_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Item_Price__c</fullName>
        <defaultValue>0.00</defaultValue>
        <label>Item Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Item__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Item</label>
        <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
        <relationshipLabel>Campaign Price Allocations</relationshipLabel>
        <relationshipName>Campaign_Item_Allocations</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Campaign Product Allocation</label>
    <nameField>
        <displayFormat>CPA-{0000}</displayFormat>
        <label>Campaign Product Allocation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Campaign Product Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Gift_Aid_Declaration__c.object
<CustomObject>
    <fields>
        <fullName>Donor__c</fullName>
        <label>Donor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Gift Aid Declarations</relationshipLabel>
        <relationshipName>Gift_Aid_Declarations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Gift_Aid_Declaration__c</fullName>
        <defaultValue>&apos;If you are a UK tax payer and tick Yes to Gift Aid the government will give us 25% on top of your donation. It doesnt cost you a penny, and helps to keep us going&apos;</defaultValue>
        <inlineHelpText>If you are a UK tax payer and tick &apos;Yes&apos; to Gift Aid the government will give us 25% on top of your donation. It doesn&apos;t cost you a penny, and helps to keep us going</inlineHelpText>
        <label>Gift Aid Declaration</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Gift_Aid_Start_Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Gift Aid Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Gift_Aid_Status__c</fullName>
        <label>Gift Aid Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>GDPR</valueSetName>
        </valueSet>
    </fields>
    <label>Gift Aid Declaration</label>
    <nameField>
        <displayFormat>GD-{00000}</displayFormat>
        <label>Gift Aid Declaration #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gift Aid Declarations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HA_Payment_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Start_Date_2__c</fullName>
        <label>Start Date -2</label>
        <type>Date</type>
    </fields>
    <label>Payment Schedule</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payment Schedules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Schedule__c.object
<CustomObject>
    <label>Deprecated Payment Schedule</label>
    <nameField>
        <displayFormat>PSN-{0}</displayFormat>
        <label>Payment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deprecated Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Payment_Schedule_Allocation__c.object
<CustomObject>
    <fields>
        <fullName>General_Accounting_Unit__c</fullName>
        <label>Item Name</label>
        <referenceTo>npsp__General_Accounting_Unit__c</referenceTo>
        <relationshipLabel>Payment Schedule Allocations</relationshipLabel>
        <relationshipName>Payment_Schedule_Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Schedule__c</fullName>
        <label>Payment Schedule</label>
        <referenceTo>HA_Payment_Schedule__c</referenceTo>
        <relationshipLabel>Payment Schedule Allocations</relationshipLabel>
        <relationshipName>Payment_Schedule_Allocations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Payment Schedule Allocation</label>
    <nameField>
        <displayFormat>PSA-{0000}</displayFormat>
        <label>Payment Schedule Allocation#</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Payment Schedule Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ramadan_Configuration__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Ramadan Configurations</description>
    <fields>
        <fullName>Start_Date_1__c</fullName>
        <label>Start Date -1</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date_2__c</fullName>
        <label>Start Date -2</label>
        <type>Date</type>
    </fields>
    <label>Ramadan Configurations</label>
</CustomObject>

classes/HA_newDonationController_Test.cls
/**
 * @description       : 
 * @author            : Iamsfdeveloper
 * @group             : 
 * @last modified on  : 02-08-2021
 * @last modified by  : Iamsfdeveloper
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   12-16-2020   Iamsfdeveloper   Initial Version
**/
@isTest
public without sharing class HA_newDonationController_Test {
    @TestSetup
    static void createData(){
        insert new Ramadan_Configuration__c(Name=String.valueOf(System.today().year()),start_Date_1__c=System.today(),start_Date_2__c=System.today()+5);
        List<HA_Payment_Schedule__c> paymentScheduleList = (List<HA_Payment_Schedule__c>)TestFactory.createSObjectList(new HA_Payment_Schedule__c(),2,'TestFactoryDefaults.PaymentSchedulesDefaults');
        insert paymentScheduleList;
        System.debug(JSON.serialize(paymentScheduleList[0]));
        List<npsp__General_Accounting_Unit__c> items = (List<npsp__General_Accounting_Unit__c>)TestFactory.createSObjectList(new npsp__General_Accounting_Unit__c(),1,'TestFactoryDefaults.GeneralAccountUnitsDefaults');
        insert items;
        Payment_Schedule_Allocation__c PSA1 = new Payment_Schedule_Allocation__c(General_Accounting_Unit__c= items[0].Id,Payment_Schedule__c = paymentScheduleList[0].Id);
        insert PSA1;
        Payment_Schedule_Allocation__c  PSA2 = new Payment_Schedule_Allocation__c(General_Accounting_Unit__c= items[0].Id,Payment_Schedule__c = paymentScheduleList[1].Id);
        insert PSA2;
        List<Contact> contactList = (List<Contact>) TestFactory.createSObjectList(
            new Contact(Email='test@humanappeal.org.uk',RecordTypeId = (String)Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Donor').getRecordTypeId()),
            1,
            true
        );
        contactlist[0].Gift_Aid_Status__c='Yes';
        update contactlist;
        insert new Gift_Aid_Declaration__c(Donor__c=contactlist[0].Id,Gift_Aid_Status__c ='Yes',Gift_Aid_Start_Date__c=System.today());
        List<Contact> orphanContact = (List<Contact>) TestFactory.createSObjectList(
            new Contact(),
            2,
            false
        );
        for(Integer i=0;i<orphanContact.size();i++){
            orphanContact[i].RecordTypeId = (String)Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Orphan').getRecordTypeId();
            orphanContact[i].LastName +=' Orphan';
            orphanContact[i].Country__c='General';
            orphanContact[i].Is_Active__c= true;

        }
        insert orphanContact;
        List<Opportunity> opplist=(List<Opportunity>) TestFactory.createSObjectList(
            new Opportunity(),
           2,
            true
        );
    } 
    testmethod static void unitTest_Positive(){
        system.assertEquals(2, [SELECT count() FROM HA_Payment_Schedule__c], 'Something went wrong');
        Test.startTest();
        HA_newDonationController.doInit();
        TestFactoryDefaults.PaymentSchedulesDefaults obj = new TestFactoryDefaults.PaymentSchedulesDefaults();
        System.debug(obj.getFieldDefaults().get(HA_Payment_Schedule__c.Name));
        System.debug('Test Schedule '+[SELECT Id FROM HA_Payment_Schedule__c  WHERE Name like 'Test Schedule%' limit 1]);
        Map<String,Object> Items_Map = HA_newDonationController.getItems('',UserInfo.getDefaultCurrency(),[SELECT Id FROM HA_Payment_Schedule__c  WHERE Name Like 'Test Schedule%' limit 1].id,'');
        Items_Map = HA_newDonationController.getItems('Donation_Item_Code__c like \'%Test1234%\'',UserInfo.getDefaultCurrency(),[SELECT Id FROM HA_Payment_Schedule__c  WHERE Name Like 'Test Schedule%' limit 1].id,'');
        HA_Logger.CreateErrorLog('Test','Contact','Testing');
        List<npsp__General_Accounting_Unit__c> Items = (List<npsp__General_Accounting_Unit__c>)Items_Map.get('items');
        system.assertEquals(1, Items.size(), 'Something went wrong');
        Test.stopTest();
    }
    @IsTest
    static void unitTest_Dialer_positive(){
        List<npsp__Trigger_Handler__c> listHandlers = npsp.TDTM_Config_API.getCachedRecords();
        npsp__Trigger_Handler__c th = new npsp__Trigger_Handler__c();
        th.Name = 'CampaignTriggerHandler_TDTM_Mutable';
        th.npsp__Class__c = 'CampaignTriggerHandler_TDTM_Mutable';
        th.npsp__Object__c = 'CampaignMember';
        th.npsp__Trigger_Action__c = 'AfterInsert';
        th.npsp__Active__c = true;
        th.npsp__Load_Order__c = 1;
        th.npsp__Asynchronous__c = false;
        listHandlers.add(th);
        Campaign OutboundCallingCampaign = new Campaign(Name='Test',Type='Outbound_Calling',Country__c='United Kingdom',Dialer_Queue__c='Dialer_Queue_UK_1');
        insert OutboundCallingCampaign;
        insert new Campaign_Product_Allocation__c(Campaign__c=OutboundCallingCampaign.Id, Item_Price__c=10.00, Item__c=[Select Id From npsp__General_Accounting_Unit__c Where Donation_Item_Code__c like '%Test1234%' limit 1].Id);
        List<Contact> contactList = [Select Id From Contact Where lastName like 'Last%' ];
        CampaignMember newMember = 
        new CampaignMember(ContactId = contactList[0].id, status='To Call', campaignid = OutboundCallingCampaign.id);
        insert newMember;
        List<Call_List__c> currentCallList = [SELECT Id,OwnerId FROM Call_List__c WHERE CampaignId__c =: OutboundCallingCampaign.Id];
        currentCallList[0].OwnerId = UserInfo.getUserId();
        ID dailerChannelId= [SELECT Id FROM ServiceChannel Where DeveloperName='Dialer_Channel' Limit 1].Id;
       
        Opportunity OPP = (Opportunity)TestFactory.createSObject(new Opportunity());
        OPP.npsp__Primary_Contact__c = contactList[0].id;

        Test.startTest();
        HA_ManageGroupMember.doInit(OutboundCallingCampaign.Id);
        HA_ManageGroupMember.saveGroupMember('[]', '[]');
        Task obj = new Task(Subject='Test',whoId = contactList[0].id,whatId = OPP.Id);
          Map<String,Object> Items_Map = HA_newDonationController.getItems('',UserInfo.getDefaultCurrency(),[SELECT Id FROM HA_Payment_Schedule__c  WHERE Name Like 'Test Schedule%' limit 1].id,OutboundCallingCampaign.Id);
	 	List<npsp__General_Accounting_Unit__c> Items =(List<npsp__General_Accounting_Unit__c>)Items_Map.get('items');
        Object[] allocationList =  new List<Object>();
        for(Integer i=0;i<2;i++){
            allocationList.add(new Map<String,String>{'npsp__General_Accounting_Unit__c'=>Items[0].Id,'npsp__Amount__c'=>'3','Stipulation_Type__c'=>'SD'});
        }
        HA_newDonationController.createTask(JSON.serialize(obj), currentCallList[0].Id);
        HA_newDonationController.createTaskAndUpdateRecord(JSON.serialize(obj),currentCallList[0].Id,JSON.serialize(contactList[0]));
        //String selectedCountry,String recordId,String selectedAge,String selectedGender,String searchParam,string[] selectedRowIds
        HA_newDonationController.getOrphanList('General',contactList[0].id,'','','',new List<String>());
        HA_newDonationController.getOrphanByNameOrId('Test','General');
        HA_newDonationController.getOrphanList('Yemen','','','','',new List<String>());
        HA_newDonationController.saveAllocation(JSON.serialize(OPP),JSON.serialize(allocationList),'['+JSON.serialize(new Map<String,String>{'Subject'=>'Test','whoId'=>contactList[0].id})+']','');
     	HA_newDonationController.getCountryList();
        Test.stopTest();
        
    }
     @IsTest
    static void unitTest_Dialer_30_10Nights(){
        StaticResource sr = [
            SELECT Id, Body
            FROM StaticResource
            WHERE Name = 'TestJSON_4'
            LIMIT 1
        ];
        String jsonBody = sr.Body.toString();
        List<Contact> contactList = [Select Id From Contact Where Email='test@humanappeal.org.uk' ];
        Opportunity OPP = (Opportunity)TestFactory.createSObject(new Opportunity(Donation_type__c='30N',Amount=6));
        OPP.npsp__Primary_Contact__c = contactList[0].id;

        Test.startTest();
        
        Task obj = new Task(Subject='Test',whoId = contactList[0].id,whatId = OPP.Id);
          List<npsp__General_Accounting_Unit__c> Items =[Select Id From npsp__General_Accounting_Unit__c];
        Object[] allocationList =  new List<Object>();
        for(Integer i=0;i<2;i++){
            allocationList.add(new Map<String,String>{'npsp__General_Accounting_Unit__c'=>Items[0].Id,'npsp__Amount__c'=>'3','Stipulation_Type__c'=>'SD'});
        }
        HA_newDonationController.saveAllocation(JSON.serialize(OPP),JSON.serialize(allocationList),'['+JSON.serialize(new Map<String,String>{'Subject'=>'Test','whoId'=>contactList[0].id})+']',jsonBody);
     
        Test.stopTest();
        
    }
}