objects/Income_Card_Payment__c.object
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <fields>
        <fullName>Order_ID__c</fullName>
        <label>Order ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Vendor__c</fullName>
        <label>Payment Vendor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Globalpay</fullName>
                </value>
                <value>
                    <fullName>SagePayPi</fullName>
                </value>
                <value>
                    <fullName>Stripe</fullName>
                </value>
                <value>
                    <fullName>SagePay</fullName>
                    <isActive>false</isActive>
                    <label>SagePay</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Full Refund</fullName>
                </value>
                <value>
                    <fullName>Partial Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Deferred_Released</fullName>
                    <label>Deferred Released</label>
                </value>
                <value>
                    <fullName>Deferred_Aborted</fullName>
                    <label>Deferred Aborted</label>
                </value>
                <value>
                    <fullName>Authenticate</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Income_Card_Payment_History__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Card_Payment__c</fullName>
        <label>Income Card Payment</label>
        <referenceTo>Income_Card_Payment__c</referenceTo>
        <relationshipName>Income_Card_Payment_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Order_ID__c</fullName>
        <label>Order ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Deferred Released</fullName>
                </value>
                <value>
                    <fullName>Deferred Aborted</fullName>
                </value>
                <value>
                    <fullName>Authenticate</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Card Payment History</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Income Card Payment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SMP_RefundController.cls
public with sharing class SMP_RefundController {    
    
    @AuraEnabled
    public static List<Income_Card_Payment_History__c> fetchIncomeCardPaymentHistory(Id incomeCardPaymentId)
    {
        return [SELECT Id, Name, Amount__c, Order_Id__c, Transaction_Type__c, Transaction_Date__c, CurrencyIsoCode  
                FROM Income_Card_Payment_History__c 
                WHERE Income_Card_Payment__c = :incomeCardPaymentId
                    AND (Transaction_Type__c = 'Sale' OR Transaction_Type__c = 'Authorised' OR Transaction_Type__c = 'Deferred Release') 
                    AND Payment_Status__c = 'Successful' order by Transaction_Date__c DESC];
    }

    @AuraEnabled
    public static Map<String, SMP_PaymentGateway.RefundResponse> executeRefundByHistory(Map<Id, Decimal> refundsByHistory)
    {
        System.debug('#### executeRefundByHistory');
        System.debug('#### refundsByHistory: ' + refundsByHistory);

        List<Income_Card_Payment_History__c> cardPayments = [SELECT Id, Name, Order_Id__c, Income_Card_Payment__c, Income_Card_Payment__r.Payment_Vendor__c, CurrencyIsoCode   
                                                            FROM Income_Card_Payment_History__c
                                                            WHERE Id =: refundsByHistory.keySet()];
        
        Map<String, SMP_PaymentGateway.RefundResponse> responseMap = new Map<String, SMP_PaymentGateway.RefundResponse>();

        for(Income_Card_Payment_History__c icph : cardPayments)
        {
            SMP_PaymentGateway.Gateway paymentGateway = SMP_PaymentGateway.getGatewayEnumByPaymentVendor(icph.Income_Card_Payment__r.Payment_Vendor__c);

            SMP_PaymentGateway.Refund refundWrapper = new SMP_PaymentGateway.Refund();
            refundWrapper.incomeCardPaymentId = icph.Income_Card_Payment__c;
            refundWrapper.amount = refundsByHistory.get(icph.Id);
            refundWrapper.currencyCode = icph.CurrencyIsoCode;

            if(paymentGateway == SMP_PaymentGateway.Gateway.SAGEPAYPI){
            }
            else if(paymentGateway == SMP_PaymentGateway.Gateway.GLOBALPAYMENTS){
            }
            else if(paymentGateway == SMP_PaymentGateway.Gateway.STRIPE){
                refundWrapper.chargeId = icph.Order_Id__c;
            }

            refundWrapper.customerPaymentReference = 'Refund';
            refundWrapper.internalPaymentDescription = 'Refund';

            SMP_PaymentGateway.RefundResponse response = SMP_PaymentGateway.doRefund(paymentGateway, refundWrapper);
            System.debug('#### response: '+response);
            responseMap.put(icph.Name, response);
        }
        
        System.debug('#### responseMap: '+responseMap);
        return responseMap;
    }
}