objects/Income_Direct_Debit__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Income_Direct_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DD_Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Bank_Sort_Code__c</fullName>
        <label>Bank Sort Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Instruction</fullName>
                    <default>true</default>
                    <label>New Instruction</label>
                </value>
                <value>
                    <fullName>First Collection</fullName>
                </value>
                <value>
                    <fullName>Ongoing Collection</fullName>
                </value>
                <value>
                    <fullName>Final Collection</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>First Represent</fullName>
                </value>
                <value>
                    <fullName>Second Represent</fullName>
                </value>
                <value>
                    <fullName>Third Represent</fullName>
                </value>
                <value>
                    <fullName>Cancelled by Payer</fullName>
                </value>
                <value>
                    <fullName>Cancelled by Originator</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Direct Debit Details</relationshipLabel>
        <relationshipName>Income_Direct_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Direct Debit Detail</label>
    <nameField>
        <displayFormat>DD{00000000}</displayFormat>
        <label>AUDDIS Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Debit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Direct_Debit_History_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Direct Debit History Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Direct_Debit_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Direct Debit Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Schedule_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Payment Schedule Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

classes/TriggerHandler_DirectDebitTest.cls
@isTest
public with sharing class TriggerHandler_DirectDebitTest
{
    @TestSetup
    static void makeData() {
        TriggerSettings__c triggersettings = new TriggerSettings__c();
        triggersettings.Direct_Debit_History_Trigger__c = true;
        triggersettings.Payment_Schedule_Trigger__c = false;
        triggersettings.Direct_Debit_Trigger__c = true;
        insert triggersettings;
    }

    @isTest static void testPaymentScheduleConnected() {
        
        Contact member = new Contact();
        member.FirstName = 'testFirst';
        member.LastName = 'testLast';
        member.Email = 'test@test.com';
        member.MailingStreet = 'test';
        member.MailingCity = 'test';
        member.MailingPostalCode = 'test';
        member.MailingState = 'test';
        member.MailingCountry = 'UK';
        insert member;

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpp';
        opp.Amount = 5;
        opp.StageName = 'test';
        opp.CloseDate = Date.Today();
        opp.npsp__Primary_Contact__c = member.Id;
        insert opp;

        Test.startTest();

        npe03__Recurring_Donation__c rd = (npe03__Recurring_Donation__c) TestFactory.createSObject(
            new npe03__Recurring_Donation__c(
                npe03__Contact__c = member.Id,
                npe03__Amount__c = 100,
                npsp__StartDate__c = Date.today(),
                npsp__PaymentMethod__c = 'Direct Debit',
                npe03__Date_Established__c = Date.today(),
                npsp__Day_of_Month__c = String.valueOf(Date.today().day()),
                Opportunity__c = opp.Id
            ),
            'TestFactoryDefaults.RDDefaults'
        );
        insert rd;

        Income_Direct_Debit__c directDebit = new Income_Direct_Debit__c(Opportunity__c = opp.Id, Contact__c = member.Id, DD_Status__c = 'On Hold', DD_Bank_Account_Number__c = '00000000', DD_Bank_Sort_Code__c = '000000');
        insert directDebit;

        Test.stopTest();
    }
}