objects/Income_Debit_History__c.object
<CustomObject>
    <fields>
        <fullName>DD_Collection_Date__c</fullName>
        <label>DD Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DD_Stage__c</fullName>
        <label>DD Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DD_Status__c</fullName>
        <label>DD Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Income_Direct_Debit__c</fullName>
        <label>Income Direct Debit</label>
        <referenceTo>Income_Direct_Debit__c</referenceTo>
        <relationshipLabel>Income Debit History</relationshipLabel>
        <relationshipName>Income_Debit_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Payment_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Schedule</label>
        <referenceTo>Payment_Schedule__c</referenceTo>
        <relationshipLabel>Income Debit History</relationshipLabel>
        <relationshipName>Income_Debit_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Income Debit History</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Income Debit History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Debit History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Income_Direct_Debit__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Income_Direct_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DD_Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Bank_Sort_Code__c</fullName>
        <label>Bank Sort Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Instruction</fullName>
                    <default>true</default>
                    <label>New Instruction</label>
                </value>
                <value>
                    <fullName>First Collection</fullName>
                </value>
                <value>
                    <fullName>Ongoing Collection</fullName>
                </value>
                <value>
                    <fullName>Final Collection</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>First Represent</fullName>
                </value>
                <value>
                    <fullName>Second Represent</fullName>
                </value>
                <value>
                    <fullName>Third Represent</fullName>
                </value>
                <value>
                    <fullName>Cancelled by Payer</fullName>
                </value>
                <value>
                    <fullName>Cancelled by Originator</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Direct Debit Details</relationshipLabel>
        <relationshipName>Income_Direct_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Direct Debit Detail</label>
    <nameField>
        <displayFormat>DD{00000000}</displayFormat>
        <label>AUDDIS Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Debit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Payment_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outstanding</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deprecated Payment Schedule</label>
    <nameField>
        <displayFormat>PSN-{0}</displayFormat>
        <label>Payment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deprecated Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Direct_Debit_History_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Direct Debit History Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Schedule_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Payment Schedule Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

classes/TriggerHandler_DirectDebitHistoryTest.cls
@isTest
public with sharing class TriggerHandler_DirectDebitHistoryTest
{
    private static void setupTestConfig(){
        TriggerSettings__c triggersettings = new TriggerSettings__c();
        triggersettings.Direct_Debit_History_Trigger__c = true;
        triggersettings.Payment_Schedule_Trigger__c = false;
        insert triggersettings;
    }

    @isTest static void testPaymentScheduleConnected() {
        setupTestConfig();

        Contact member = new Contact();
        member.FirstName = 'testFirst';
        member.LastName = 'testLast';
        insert member;

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpp';
        opp.Amount = 5;
        opp.StageName = 'test';
        opp.CloseDate = Date.Today();
        insert opp;

        Income_Direct_Debit__c directDebit = new Income_Direct_Debit__c(Opportunity__c = opp.Id, Contact__c = member.Id, DD_Status__c = 'Ongoing Collection', DD_Bank_Account_Number__c = '00000000', DD_Bank_Sort_Code__c = '000000');
        insert directDebit;

        Payment_Schedule__c schedule = new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Schedule_Date__c = Date.Today() + 5);
        insert schedule;

        Income_Debit_History__c directDebitHistory = new Income_Debit_History__c(Income_Direct_Debit__c = directDebit.Id, DD_Status__c = 'Ongoing Collection', DD_Collection_Date__c = Date.Today() + 5);
        insert directDebitHistory;
    }

    @isTest static void testPaymentScheduleSetToFailed() {
        setupTestConfig();

        Contact member = new Contact();
        member.FirstName = 'testFirst';
        member.LastName = 'testLast';
        insert member;

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpp';
        opp.Amount = 5;
        opp.StageName = 'test';
        opp.CloseDate = Date.Today();
        insert opp;

        Income_Direct_Debit__c directDebit = new Income_Direct_Debit__c(Opportunity__c = opp.Id, Contact__c = member.Id, DD_Status__c = 'Ongoing Collection', DD_Bank_Account_Number__c = '00000000', DD_Bank_Sort_Code__c = '000000');
        insert directDebit;

        Payment_Schedule__c schedule = new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Schedule_Date__c = Date.Today() + 5);
        insert schedule;

        Income_Debit_History__c directDebitHistory = new Income_Debit_History__c(Payment_Schedule__c = schedule.Id, 
                                                                                Income_Direct_Debit__c = directDebit.Id, 
                                                                                DD_Status__c = 'Ongoing Collection', 
                                                                                DD_Collection_Date__c = Date.Today() + 5);
        insert directDebitHistory;

        directDebitHistory.DD_Stage__c = 'Failed';
        update directDebitHistory;      

    }

    @isTest static void testPaymentScheduleSetToSuccess() {
        setupTestConfig();

        Contact member = new Contact();
        member.FirstName = 'testFirst';
        member.LastName = 'testLast';        
        insert member;

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpp';
        opp.Amount = 5;
        opp.StageName = 'test';
        opp.CloseDate = Date.Today();
        insert opp;

        Income_Direct_Debit__c directDebit = new Income_Direct_Debit__c(Opportunity__c = opp.Id, Contact__c = member.Id, DD_Status__c = 'Ongoing Collection', DD_Bank_Account_Number__c = '00000000', DD_Bank_Sort_Code__c = '000000');
        insert directDebit;

        Payment_Schedule__c schedule = new Payment_Schedule__c(Opportunity__c = opp.Id,Status__c = 'Outstanding', Schedule_Date__c = Date.Today() + 5);
        insert schedule;

        Income_Debit_History__c directDebitHistory = new Income_Debit_History__c(Payment_Schedule__c = schedule.Id, 
                                                                                Income_Direct_Debit__c = directDebit.Id, 
                                                                                DD_Status__c = 'Ongoing Collection', 
                                                                                DD_Collection_Date__c = Date.Today() + 5);
        insert directDebitHistory;

        directDebitHistory.DD_Stage__c = 'Successful';
        update directDebitHistory;      
    }
}