objects/Income_Card_Payment__c.object
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <fields>
        <fullName>Internal_Payment_Description__c</fullName>
        <label>Internal Payment Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Card Payment Details</relationshipLabel>
        <relationshipName>Income_Card_Payment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recurring_Donation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recurring Donation</label>
        <referenceTo>npe03__Recurring_Donation__c</referenceTo>
        <relationshipLabel>Card Payment Details</relationshipLabel>
        <relationshipName>Card_Payment_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source_Card_Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Source Card Payment</label>
        <referenceTo>Income_Card_Payment__c</referenceTo>
        <relationshipLabel>Card Payment Details</relationshipLabel>
        <relationshipName>Card_Payment_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Full Refund</fullName>
                </value>
                <value>
                    <fullName>Partial Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Deferred_Released</fullName>
                    <label>Deferred Released</label>
                </value>
                <value>
                    <fullName>Deferred_Aborted</fullName>
                    <label>Deferred Aborted</label>
                </value>
                <value>
                    <fullName>Authenticate</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Income_Card_Payment_History__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Income_Card_Payment__c</fullName>
        <label>Income Card Payment</label>
        <referenceTo>Income_Card_Payment__c</referenceTo>
        <relationshipName>Income_Card_Payment_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Internal_Payment_Description__c</fullName>
        <label>Internal Payment Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Schedule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment Schedule</label>
        <referenceTo>Payment_Schedule__c</referenceTo>
        <relationshipName>Income_Card_Payment_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Deferred Released</fullName>
                </value>
                <value>
                    <fullName>Deferred Aborted</fullName>
                </value>
                <value>
                    <fullName>Authenticate</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Card Payment History</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Income Card Payment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Payment_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Payment_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Deprecated Payment Schedule</label>
    <nameField>
        <displayFormat>PSN-{0}</displayFormat>
        <label>Payment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deprecated Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TriggerHandler_CardPayment.cls
public without sharing class TriggerHandler_CardPayment {
    public static void OnBeforeInsert(List<Income_Card_Payment__c> newRecords)
    {
    }

    public static void OnAfterInsert(Map<Id, Income_Card_Payment__c> newRecords)
    {        
    }

    public static void OnBeforeUpdate(Map<Id, Income_Card_Payment__c> newRecords, Map<Id, Income_Card_Payment__c> oldRecords)
    {
            
    }
    
    public static void OnAfterUpdate(Map<Id, Income_Card_Payment__c> newRecords, Map<Id, Income_Card_Payment__c> oldRecords)
    {        
        List<npe03__Recurring_Donation__c> recurringDonations = new List<npe03__Recurring_Donation__c>();

        List<Income_Card_Payment__c> clonedCardPayment = new List<Income_Card_Payment__c>();
        List<Income_Card_Payment_History__c> clonedHistories = new List<Income_Card_Payment_History__c>();
        Set<String> oppIds = new Set<String>();

        for(Income_Card_Payment__c card : newRecords.values())
        {
            if(card.Payment_Status__c == 'Successful' && oldRecords.get(card.Id).Payment_Status__c != 'Successful' 
                && (card.Transaction_Type__c == 'Sale' || card.Transaction_Type__c == 'Authenticate'))
            {                             
                if(card.Recurring_Donation__c != null)
                {
                    recurringDonations.add(new npe03__Recurring_Donation__c(Id = card.Recurring_Donation__c, Card_Payment_Detail__c = card.Id));
                }
                else 
                {
                    if(card.Opportunity__c != null)
                    {
                        oppIds.add(card.Opportunity__c);
                    } 

                    System.debug('#### card.Internal_Payment_Description__c: ' + card.Internal_Payment_Description__c);

                    if(String.isNotBlank(card.Internal_Payment_Description__c))
                    {
                        List<String> additionalOpportunityIds = card.Internal_Payment_Description__c.split(',');

                        for(String s : additionalOpportunityIds)
                        {
                            if (s instanceOf Id)
                            {
                                oppIds.add(s);
                                Income_Card_Payment__c clone = card.clone();
                                clone.Opportunity__c = s;
                                clone.Source_Card_Payment__c = card.Id;
                                clonedCardPayment.add(clone);
                            }
                        }
                    }
                }
                
            }
        }

        if(recurringDonations.size() > 0)
        {
            update recurringDonations;
        }

        if(oppIds.Size() > 0)
        {
            Map<Id, Opportunity> opportunities = new Map<Id, Opportunity>([SELECT Id, Amount, StageName, Payment_Schedule__r.Frequency__c FROM Opportunity WHERE Id IN :oppIds]);

            if(clonedCardPayment.Size() > 0)
            {
                insert clonedCardPayment;

                for(Income_Card_Payment__c payment : clonedCardPayment)
                {
                    Opportunity opp = opportunities.get(payment.Opportunity__c);
                    
                    System.debug('#### payment: ' + payment);
                    System.debug('#### opp: ' + opp);

                    Income_Card_Payment_History__c clone = new Income_Card_Payment_History__c();
                    clone.CurrencyIsoCode = payment.CurrencyIsoCode;
                    clone.Income_Card_Payment__c = payment.Id;
                    clone.Payment_Status__c = 'Successful';                
                    clone.Transaction_Date__c = DateTime.now();

                    if(opp.Payment_Schedule__r.Frequency__c == 'Single')
                    {
                        clone.Transaction_Type__c = 'Sale';
                        clone.Amount__c = opp.Amount;
                    }
                    else
                    {
                        // Must be a recurring payment schedule
                        clone.Transaction_Type__c = 'Authenticate';
                        clone.Amount__c = 0.00;
                    }

                    clonedHistories.add(clone);
                }

                System.debug('#### clonedHistories: ' + clonedHistories);

                if(clonedHistories.Size() > 0)
                {
                    insert clonedHistories;
                }
            }
        
            for(Opportunity opp : opportunities.values())
            {
                opp.StageName = 'Paid';
            }

            update opportunities.values();
        }        
    }
}