objects/Income_Card_Payment__c.object
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <fields>
        <fullName>Gateway_Customer_Reference__c</fullName>
        <label>Gateway Customer Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Vendor__c</fullName>
        <label>Payment Vendor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Globalpay</fullName>
                </value>
                <value>
                    <fullName>SagePayPi</fullName>
                </value>
                <value>
                    <fullName>Stripe</fullName>
                </value>
                <value>
                    <fullName>SagePay</fullName>
                    <isActive>false</isActive>
                    <label>SagePay</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RP_Amount__c</fullName>
        <label>RP Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RP_Collection_Day__c</fullName>
        <label>RP Collection Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RP_Description__c</fullName>
        <label>RP Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RP_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RP Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RP_End_Date__c</fullName>
        <description>The date after which no further Repeat Payment will be taken</description>
        <inlineHelpText>Date after which no further Repeat Payments will be taken, blank means for ever.</inlineHelpText>
        <label>RP End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RP_Frequency__c</fullName>
        <label>RP Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RP_Next_Payment_Date__c</fullName>
        <label>RP Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RP_Start_Date__c</fullName>
        <label>RP Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RP_Stretch__c</fullName>
        <label>RP Stretch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Full Refund</fullName>
                </value>
                <value>
                    <fullName>Partial Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Deferred_Released</fullName>
                    <label>Deferred Released</label>
                </value>
                <value>
                    <fullName>Deferred_Aborted</fullName>
                    <label>Deferred Aborted</label>
                </value>
                <value>
                    <fullName>Authenticate</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SMP_RepeatPaymentSchedulerBatch.cls
global class SMP_RepeatPaymentSchedulerBatch implements Database.AllowsCallouts, Database.Batchable<sObject>
{
    global Boolean isMultiCurrencyEnabled = Schema.getGlobalDescribe().containsKey('CurrencyType');
    global List<Income_Card_Payment__c> failedCardPayments;

    global Database.QueryLocator start(Database.BatchableContext bc)
    {
        System.debug('#### SMP_RepeatPaymentSchedulerBatch Start');
        System.debug('#### isMultiCurrencyEnabled: ' + isMultiCurrencyEnabled);

        failedCardPayments = new List<Income_Card_Payment__c>();

        String query = 'SELECT Id, Name, Transaction_Type__c, Payment_Vendor__c, Transaction_ID__c, Gateway_Customer_Reference__c, ';
        query += 'RP_Stretch__c, RP_Collection_Day__c, RP_Start_Date__c, RP_Next_Payment_Date__c, RP_Frequency__c, RP_End_Date__c, RP_Enabled__c, RP_Description__c, RP_Amount__c';

        if(isMultiCurrencyEnabled){
            query += ', CurrencyIsoCode';
        }

        query += ' FROM Income_Card_Payment__c';
        query += ' WHERE RP_Enabled__c = TRUE AND RP_Next_Payment_Date__c = TODAY AND (RP_End_Date__c = null OR RP_End_Date__c >= TODAY) AND Payment_Vendor__c != null AND Payment_Status__c = \'Successful\'';
        query += ' AND (Transaction_Type__c = \'Sale\' OR Transaction_Type__c = \'Authenticate\'  OR Transaction_Type__c = \'Authorised\'  OR Transaction_Type__c = \'Deferred\' OR Transaction_Type__c = \'Deferred Released\')';

        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Income_Card_Payment__c> cardPayments)
    {    
        System.debug('#### SMP_RepeatPaymentSchedulerBatch execute');
        System.debug('#### cardPayments: ' + cardPayments);
        System.debug('#### isMultiCurrencyEnabled: ' + isMultiCurrencyEnabled);        

        if(failedCardPayments == null){
            failedCardPayments = new List<Income_Card_Payment__c>();
        }

        List<Income_Card_Payment__c> updatedCardPayments = new List<Income_Card_Payment__c>();

        for(Income_Card_Payment__c icp : cardPayments)
        {
            if(String.isNotBlank(icp.Payment_Vendor__c))
            {
                SMP_PaymentGateway.Gateway paymentGateway = SMP_PaymentGateway.getGatewayEnumByPaymentVendor(icp.Payment_Vendor__c);
                System.debug('#### paymentGateway: ' + paymentGateway);

                if(paymentGateway != null)
                {
                    if(icp.Transaction_Type__c == 'Sale' || icp.Transaction_Type__c == 'Authorised' || icp.Transaction_Type__c == 'Deferred Released')
                    {
                        // We do a normal repeat payment here.
                        System.debug('#### Process Repeat Payment');

                        SMP_PaymentGateway.RepeatPayment repeatWrapper = new SMP_PaymentGateway.RepeatPayment();
                        repeatWrapper.incomeCardPaymentId = icp.Id;
                        repeatWrapper.amount = icp.RP_Amount__c;

                        // if CurrencyIsoCode exists use that
                        repeatWrapper.currencyCode = isMultiCurrencyEnabled ? String.valueOf(icp.get('CurrencyIsoCode')) : UserInfo.getDefaultCurrency();
                        repeatWrapper.customerPaymentReference = 'test';
                        repeatWrapper.internalPaymentDescription = 'test';
                        
                        if(paymentGateway == SMP_PaymentGateway.Gateway.SAGEPAYPI){                            
                        }
                        else if(paymentGateway == SMP_PaymentGateway.Gateway.GLOBALPAYMENTS){

                        }
                        else if(paymentGateway == SMP_PaymentGateway.Gateway.STRIPE){
                            repeatWrapper.customerId = icp.Gateway_Customer_Reference__c;
                        }

                        SMP_PaymentGateway.RepeatPaymentResponse response = SMP_PaymentGateway.doRepeatPayment(paymentGateway, repeatWrapper);

                        System.debug('#### response: ' + response);

                        Boolean isSuccess = response != null && response.status == 'success' ? true : false;
                        updatedCardPayments.add(handleResponse(icp, isSuccess));
                    }
                    else if(icp.Transaction_Type__c == 'Authenticate')
                    {
                        // We do a authenticate/authorise release here.
                        System.debug('#### Process Authenticate Authorise');

                        SMP_PaymentGateway.AuthenticateAuthoriseRelease authoriseWrapper = new SMP_PaymentGateway.AuthenticateAuthoriseRelease();
                        authoriseWrapper.incomeCardPaymentId = icp.Id;
                        authoriseWrapper.amount = icp.RP_Amount__c;

                        // if CurrencyIsoCode exists use that
                        authoriseWrapper.currencyCode = isMultiCurrencyEnabled ? String.valueOf(icp.get('CurrencyIsoCode')) : UserInfo.getDefaultCurrency();
                        authoriseWrapper.customerPaymentReference = icp.RP_Description__c;
                        authoriseWrapper.internalPaymentDescription = 'test';
                        if(paymentGateway == SMP_PaymentGateway.Gateway.SAGEPAYPI){                            
                        }
                        else if(paymentGateway == SMP_PaymentGateway.Gateway.GLOBALPAYMENTS){

                        }
                        else if(paymentGateway == SMP_PaymentGateway.Gateway.STRIPE){
                            authoriseWrapper.customerId = icp.Gateway_Customer_Reference__c;
                        }

                        SMP_PaymentGateway.AuthenticateAuthoriseReleaseResponse response = SMP_PaymentGateway.doAuthenticateAuthoriseRelease(paymentGateway, authoriseWrapper);

                        System.debug('#### response: ' + response);

                        Boolean isSuccess = response != null && response.status == 'success' ? true : false;
                        updatedCardPayments.add(handleResponse(icp, isSuccess));
                    }
                    else if(icp.Transaction_Type__c == 'Deferred')
                    {
                        // We do a defer release here.
                        System.debug('#### Process Defer Release');

                        SMP_PaymentGateway.DeferredRelease releaseWrapper = new SMP_PaymentGateway.DeferredRelease();
                        releaseWrapper.incomeCardPaymentId = icp.Id;
                        releaseWrapper.amount = icp.RP_Amount__c;

                        // if CurrencyIsoCode exists use that
                        releaseWrapper.currencyCode = isMultiCurrencyEnabled ? String.valueOf(icp.get('CurrencyIsoCode')) : UserInfo.getDefaultCurrency();
                        releaseWrapper.customerPaymentReference = icp.RP_Description__c;
                        
                        if(paymentGateway == SMP_PaymentGateway.Gateway.SAGEPAYPI){                            
                        }
                        else if(paymentGateway == SMP_PaymentGateway.Gateway.GLOBALPAYMENTS){

                        }
                        else if(paymentGateway == SMP_PaymentGateway.Gateway.STRIPE){
                            releaseWrapper.customerId = icp.Gateway_Customer_Reference__c;
                        }

                        SMP_PaymentGateway.DeferredReleaseResponse response = SMP_PaymentGateway.doDeferredRelease(paymentGateway, releaseWrapper);

                        System.debug('#### response: ' + response);

                        Boolean isSuccess = response != null && response.status == 'success' ? true : false;
                        updatedCardPayments.add(handleResponse(icp, isSuccess));
                    }
                }                
            }            
        }

        update updatedCardPayments;
    }
    
    global void finish(Database.BatchableContext BC)
    {        
    }

    private Income_Card_Payment__c handleResponse(Income_Card_Payment__c cardPayment, Boolean isSuccess){

        System.debug('#### handleResponse');
        System.debug('#### cardPayment: ' + cardPayment);
        System.debug('#### isSuccess: ' + isSuccess);

        Income_Card_Payment__c newCardPayment = new Income_Card_Payment__c(Id = cardPayment.Id);

        if(isSuccess == true)
        {    
            // If management of dates is switched on, update the repeat payment date.
            if(SMP_PaymentGateway.paymentConfig.Manage_Repeat_Payment_Dates__c == true)
            {
                System.debug('#### Calculating Next Payment Date');
                
                newCardPayment.RP_Next_Payment_Date__c = SMP_PaymentGateway.getNextRepeatPaymentDate(cardPayment.RP_Stretch__c,
                                                                                                    cardPayment.RP_Frequency__c,
                                                                                                    cardPayment.RP_Collection_Day__c,
                                                                                                    cardPayment.RP_Next_Payment_Date__c,
                                                                                                    cardPayment.RP_End_Date__c);

                System.debug('#### Next Payment Date: ' + newCardPayment.RP_Next_Payment_Date__c);
            }        
        }
        else
        {     
            failedCardPayments.add(cardPayment); 
        } 
        
        return newCardPayment;
    }
}