objects/Income_Card_Payment__c.object
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <fields>
        <fullName>Authorisation_Code__c</fullName>
        <label>Authorisation Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Authorisation_Date__c</fullName>
        <label>Authorisation Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Card_Expiry_Date__c</fullName>
        <label>Card Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Card_Number_Ending__c</fullName>
        <label>Card Number Ending</label>
        <length>16</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Card_Type__c</fullName>
        <label>Card Type</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Income_Card_Payment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Internal_Payment_Description__c</fullName>
        <label>Internal Payment Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_On_Card__c</fullName>
        <label>Name On Card</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Card Payment Details</relationshipLabel>
        <relationshipName>Income_Card_Payment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_ID__c</fullName>
        <label>Order ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Reference__c</fullName>
        <label>Payment Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Vendor__c</fullName>
        <label>Payment Vendor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Globalpay</fullName>
                </value>
                <value>
                    <fullName>SagePayPi</fullName>
                </value>
                <value>
                    <fullName>Stripe</fullName>
                </value>
                <value>
                    <fullName>SagePay</fullName>
                    <isActive>false</isActive>
                    <label>SagePay</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Donation_Type</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Full Refund</fullName>
                </value>
                <value>
                    <fullName>Partial Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Deferred_Released</fullName>
                    <label>Deferred Released</label>
                </value>
                <value>
                    <fullName>Deferred_Aborted</fullName>
                    <label>Deferred Aborted</label>
                </value>
                <value>
                    <fullName>Authenticate</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <recordTypes>
        <fullName>Card_Payment</fullName>
        <active>true</active>
        <label>Card Payment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Income_Card_Payment_History__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Authorisation_Code__c</fullName>
        <label>Authorisation Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Income_Card_Payment__c</fullName>
        <label>Income Card Payment</label>
        <referenceTo>Income_Card_Payment__c</referenceTo>
        <relationshipName>Income_Card_Payment_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Internal_Payment_Description__c</fullName>
        <label>Internal Payment Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Order_ID__c</fullName>
        <label>Order ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Reference__c</fullName>
        <label>Payment Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Date__c</fullName>
        <label>Transaction Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Deferred Released</fullName>
                </value>
                <value>
                    <fullName>Deferred Aborted</fullName>
                </value>
                <value>
                    <fullName>Authenticate</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Card Payment History</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Income Card Payment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment History</pluralLabel>
    <recordTypes>
        <fullName>Card_Payment</fullName>
        <active>true</active>
        <label>Card Payment</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TriggerHandler_CardPaymentHistory.cls
public without sharing class TriggerHandler_CardPaymentHistory {
    public static void OnBeforeInsert(List<Income_Card_Payment_History__c> newRecords)
    {
       
    }

    public static void OnAfterInsert(Map<Id, Income_Card_Payment_History__c> newRecords)
    {
        List<npe01__OppPayment__c> npspPaymentRecordList = new List<npe01__OppPayment__c>();
        Set<String> guidSet = new Set<String>();
        Set<Id> cardPaymentIds = new Set<Id>();
        List<Income_Card_Payment_History__c> successfulSales = new List<Income_Card_Payment_History__c>();
        List<Income_Card_Payment_History__c> successfulRefunds = new List<Income_Card_Payment_History__c>();

        for(Income_Card_Payment_History__c cardPaymentHistory : newRecords.values()){
            cardPaymentIds.add(cardPaymentHistory.Income_Card_Payment__c);

            if(cardPaymentHistory.Transaction_Type__c == 'Sale' && cardPaymentHistory.Payment_Status__c == 'Successful'){
                successfulSales.add(cardPaymentHistory);

                if(String.isNotBlank(cardPaymentHistory.Internal_Payment_Description__c)){
                    guidSet.add(cardPaymentHistory.Internal_Payment_Description__c);
                }
            }

            if(cardPaymentHistory.Transaction_Type__c == 'Refund' && cardPaymentHistory.Payment_Status__c == 'Successful'){
                successfulRefunds.add(cardPaymentHistory);

                if(String.isNotBlank(cardPaymentHistory.Internal_Payment_Description__c)){
                    guidSet.add(cardPaymentHistory.Internal_Payment_Description__c);
                }
            }
        }

        Map<Id, Income_Card_Payment__c> cardPaymentMap = new Map<Id, Income_Card_Payment__c>(
                                                                    [SELECT Id, Name, Authorisation_Date__c, Card_Expiry_Date__c, 
                                                                        Card_Number_Ending__c, Card_Type__c, Name_On_Card__c, 
                                                                        Opportunity__c, Payment_Vendor__c, Status__c, Contact__c 
                                                                    FROM Income_Card_Payment__c
                                                                    WHERE Id IN :cardPaymentIds]);
                            
        List<Opportunity> opps = getOpportunties(guidSet);

        npspPaymentRecordList.addAll(generateNPSPPayments(successfulSales, opps, cardPaymentMap));
        npspPaymentRecordList.addAll(generateNPSPPayments(successfulRefunds, opps, cardPaymentMap));

        if(npspPaymentRecordList.Size() > 0){
            try {
                insert npspPaymentRecordList;
            } catch (Exception e) {
                System.debug('#### NPSP Payment Failed To Insert');
            }            
        }
    }

    public static void OnBeforeUpdate(Map<Id, Income_Card_Payment_History__c> newRecords, Map<Id, Income_Card_Payment_History__c> oldRecords)
    {
    }
    
    public static void OnAfterUpdate(Map<Id, Income_Card_Payment_History__c> newRecords, Map<Id, Income_Card_Payment_History__c> oldRecords)
    {
    }

    private static List<Opportunity> getOpportunties(Set<String> guidSet) {
        return (List<Opportunity>) [
            SELECT Id, StageName, GUID__c, npsp__Primary_Contact__c 
            FROM Opportunity
            WHERE Id IN :guidSet
        ];
    }

    private static List<npe01__OppPayment__c> generateNPSPPayments(List<Income_Card_Payment_History__c> histories, List<Opportunity> opps, Map<Id, Income_Card_Payment__c> cardPayments)
    {
        List<npe01__OppPayment__c> npspPayments = new List<npe01__OppPayment__c>();

        for(Income_Card_Payment_History__c history : histories) {
            Boolean oppFound = false;
            Income_Card_Payment__c cardPayment = cardPayments.get(history.Income_Card_Payment__c);
            
            npe01__OppPayment__c payment = new npe01__OppPayment__c();
            /*Card Payment RecordType*/
            payment.Card_Payment_History__c = history.Id;
            payment.npe01__Payment_Method__c = 'Credit Card';
            payment.CurrencyIsoCode = history.CurrencyIsoCode;
            payment.npe01__Paid__c = true;
            payment.npe01__Payment_Date__c = Date.valueOf(history.Transaction_Date__c);
            
            if(history.Transaction_Type__c == 'Refund'){
                payment.npe01__Payment_Amount__c = history.Amount__c * -1;
                payment.npsp__Type__c = 'Refund';
            }
            else{
                payment.RecordTypeId = Schema.SObjectType.npe01__OppPayment__c.getRecordTypeInfosByDeveloperName().get('Card_Payment').getRecordTypeId();
                
                payment.Payment_Reference__c = history.Internal_Payment_Description__c;
                payment.Order_Id__c = history.Order_Id__c;
                payment.Authorisation_Code__c = history.Authorisation_Code__c;
                payment.npsp__Authorized_Date__c = history.Transaction_Date__c;
                payment.npsp__Authorized_UTC_Timestamp__c = string.valueOf(history.Transaction_Date__c);
                payment.npsp__Card_Last_4__c = cardPayment.Card_Number_Ending__c;
                payment.npsp__Card_Network__c = cardPayment.Card_Type__c;
                payment.Card_Type__c = cardPayment.Card_Type__c;        
                payment.Name_On_Card__c = cardPayment.Name_On_Card__c;
                payment.Payment_Vendor__c = cardPayment.Payment_Vendor__c;
                payment.npe01__Payment_Amount__c = history.Amount__c;
                payment.npsp__Type__c = 'Sale';
                payment.Transaction_Type__c = 'Sale';
                /*Card Expiry Details*/
                if(cardPayment.Card_Expiry_Date__c != null){
                    payment.npsp__Card_Expiration_Month__c = String.valueOf(cardPayment.Card_Expiry_Date__c.month());
                    payment.npsp__Card_Expiration_Year__c = String.valueOf(cardPayment.Card_Expiry_Date__c.year());
                }
            }

            for(Opportunity o : opps) {
                if(history.Internal_Payment_Description__c == o.Id) {                   
                    // Must be a repeat card payment.
                    payment.npe01__Opportunity__c = o.Id;                    
                    payment.Contact__c = o.npsp__Primary_Contact__c;
                    payment.Status__c = 'RD'; 
                    
                    oppFound = true;
                }
            }

            if(oppFound == false) {
                // Must be a single card payment.
                payment.Status__c = 'SD';
                payment.npe01__Opportunity__c = cardPayment.Opportunity__c;
                payment.Contact__c = cardPayment.Contact__c;                
            }

            if(payment.npe01__Opportunity__c != null)
            {
                npspPayments.add(payment);
            }            
        }
        
        return npspPayments;
    }
}