objects/Income_Card_Payment__c.object
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <fields>
        <fullName>Gateway_Customer_Reference__c</fullName>
        <label>Gateway Customer Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Internal_Payment_Description__c</fullName>
        <label>Internal Payment Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Card Payment Details</relationshipLabel>
        <relationshipName>Income_Card_Payment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Status_Details__c</fullName>
        <label>Payment Status Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Full Refund</fullName>
                </value>
                <value>
                    <fullName>Partial Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Deferred_Released</fullName>
                    <label>Deferred Released</label>
                </value>
                <value>
                    <fullName>Deferred_Aborted</fullName>
                    <label>Deferred Aborted</label>
                </value>
                <value>
                    <fullName>Authenticate</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Income_Card_Payment_History__c.object
<CustomObject>
    <fields>
        <fullName>Income_Card_Payment__c</fullName>
        <label>Income Card Payment</label>
        <referenceTo>Income_Card_Payment__c</referenceTo>
        <relationshipName>Income_Card_Payment_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Internal_Payment_Description__c</fullName>
        <label>Internal Payment Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Payment_Status_Details__c</fullName>
        <label>Payment Status Details</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Deferred Released</fullName>
                </value>
                <value>
                    <fullName>Deferred Aborted</fullName>
                </value>
                <value>
                    <fullName>Authenticate</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Card Payment History</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Income Card Payment History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Card_Payment_History_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Card Payment History Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Card_Payment_Trigger__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Card Payment Trigger</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Payment_Schedule_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Payment Schedule Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

classes/PaymentEventCardPaymentHandlerTest.cls
/**
 * @description       : Apex Test for PaymentEventCardPaymentHandler
 * @author            : agentgill
 * @group             :
 * @last modified on  : 07-11-2020
 * @last modified by  : agentgill
 * Modifications Log
 * Ver   Date         Author      Modification
 * 1.0   07-05-2020   agentgill   Initial Version
 **/
@isTest
public with sharing class PaymentEventCardPaymentHandlerTest {
    @TestSetup
    static void makeData() {
        List<Contact> contacts = (List<Contact>) TestFactory.createSObjectList(
            new Contact(Email = 'test@test.com'),
            1,
            true
        );

        List<npe03__Recurring_Donation__c> rds = new List<npe03__Recurring_Donation__c>();

        for (Contact c : [
            SELECT Id, AccountId
            FROM Contact
            WHERE Id IN :contacts
        ]) {
            npe03__Recurring_Donation__c rd = (npe03__Recurring_Donation__c) TestFactory.createSObject(
                new npe03__Recurring_Donation__c(
                    npe03__Contact__c = c.Id,
                    npe03__Amount__c = 100,
                    npsp__StartDate__c = Date.today(),
                    npsp__PaymentMethod__c = 'Card Payment',
                    npe03__Date_Established__c = Date.today(),
                    npsp__Day_of_Month__c = String.valueOf(Date.today().day())
                ),
                'TestFactoryDefaults.RDDefaults'
            );
            rds.add(rd);
        }

        insert rds;

        TriggerSettings__c triggersettings = new TriggerSettings__c();
        triggersettings.Card_Payment_History_Trigger__c = true;
        triggersettings.Card_Payment_Trigger__c = true;
        triggersettings.Payment_Schedule_Trigger__c = false;
        insert triggersettings;
    }

    /**
     * @description Test Successful Card Payment
     * @author agentgill | 07-05-2020
     **/
    @isTest
    private static void testSuccessfulProcessCardPaymentEvent() {
        Opportunity opp = [
            SELECT Id, Name, StageName, AccountId, GUID__c
            FROM Opportunity
            LIMIT 1
        ];

        opp.GUID__c = 'TESTGUID';
        update opp;

        System.debug('!!! testOpp' + opp);
        Income_Card_Payment__c cp = new Income_Card_Payment__c(
            Opportunity__c = opp.Id,
            Payment_Status__c = 'Test',
            Transaction_Type__c = 'Authenticate',
            Gateway_Customer_Reference__c = 'Test'
        );
        insert cp;
        System.debug('!!! cardPayment' + cp);

        Test.startTest();

        Income_Card_Payment_History__c cph = new Income_Card_Payment_History__c(
            Income_Card_Payment__c = cp.Id,
            Payment_Status__c = 'Successful',
            Payment_Status_Details__c = 'Successful payment',
            Internal_Payment_Description__c = opp.Id,
            Transaction_Type__c = 'Sale'
        );

        insert cph;

        Test.stopTest();

        System.assertEquals(
            'Paid',
            [SELECT Id, StageName FROM Opportunity]
            .StageName,
            'Something went wrong'
        );
    }

    @isTest
    private static void testFailedProcessCardPaymentEvent() {
        Opportunity opp = [
            SELECT Id, Name, StageName, AccountId, GUID__c
            FROM Opportunity
            LIMIT 1
        ];

        opp.GUID__c = 'TESTGUID';
        update opp;

        System.debug('!!! testOpp' + opp);
        Income_Card_Payment__c cp = new Income_Card_Payment__c(
            Opportunity__c = opp.Id,
            Payment_Status__c = 'Test',
            Transaction_Type__c = 'Authenticate',
            Gateway_Customer_Reference__c = 'Test'
        );
        insert cp;
        System.debug('!!! cardPayment' + cp);

        Test.startTest();

        Income_Card_Payment_History__c cph = new Income_Card_Payment_History__c(
            Income_Card_Payment__c = cp.Id,
            Payment_Status__c = 'Failed',
            Payment_Status_Details__c = 'Failed payment',
            Internal_Payment_Description__c = opp.Id,
            Transaction_Type__c = 'Sale'
        );

        insert cph;

        Test.stopTest();

        System.assertEquals(
            'Payment Failed',
            [SELECT Id, StageName FROM Opportunity]
            .StageName,
            'Something went wrong'
        );
    }
}