objects/Income_Card_Payment__c.object
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Card Payment Details</relationshipLabel>
        <relationshipName>Income_Card_Payment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RP_Amount__c</fullName>
        <label>RP Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RP_Collection_Day__c</fullName>
        <label>RP Collection Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RP_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RP Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RP_Frequency__c</fullName>
        <label>RP Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RP_Next_Payment_Date__c</fullName>
        <label>RP Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RP_Start_Date__c</fullName>
        <label>RP Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Donation_Type</valueSetName>
        </valueSet>
    </fields>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Income_Direct_Debit__c.object
<CustomObject>
    <fields>
        <fullName>DD_Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Bank_Sort_Code__c</fullName>
        <label>Bank Sort Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Collection_Period__c</fullName>
        <label>Collection Period</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                    <default>true</default>
                    <label>Monthly</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DD_First_Collection_Amount__c</fullName>
        <label>First Collection Amount</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DD_First_Collection_Date__c</fullName>
        <inlineHelpText>This is set by the DD collection engine</inlineHelpText>
        <label>First Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DD_Next_Collection_Date__c</fullName>
        <inlineHelpText>This is set by the DD Collection Engine</inlineHelpText>
        <label>Next Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DD_Ongoing_Collection_Amount__c</fullName>
        <label>Ongoing Collection Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DD_Start_Date__c</fullName>
        <inlineHelpText>DDs will not be collected before this date</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DD_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Instruction</fullName>
                    <default>true</default>
                    <label>New Instruction</label>
                </value>
                <value>
                    <fullName>First Collection</fullName>
                </value>
                <value>
                    <fullName>Ongoing Collection</fullName>
                </value>
                <value>
                    <fullName>Final Collection</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>First Represent</fullName>
                </value>
                <value>
                    <fullName>Second Represent</fullName>
                </value>
                <value>
                    <fullName>Third Represent</fullName>
                </value>
                <value>
                    <fullName>Cancelled by Payer</fullName>
                </value>
                <value>
                    <fullName>Cancelled by Originator</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Direct Debit Details</relationshipLabel>
        <relationshipName>Income_Direct_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Direct Debit Detail</label>
    <nameField>
        <displayFormat>DD{00000000}</displayFormat>
        <label>AUDDIS Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Debit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Payment_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outstanding</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deprecated Payment Schedule</label>
    <nameField>
        <displayFormat>PSN-{0}</displayFormat>
        <label>Payment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deprecated Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/SMP_PaymentScheduleHelperTest.cls
@isTest
private class SMP_PaymentScheduleHelperTest {
    /* private static Opportunity opportunity;
    private static Contact contact;

    private static void setupConfig()
    {
        String responseBody = '{"ProcessListNewDDFirstCollectionDateResult":[{"Error":"","FirstCollectionDate":"2019-01-06"}]}';
        
        HttpRestCallOutMock fakeResponse = new HttpRestCallOutMock(200, responseBody);
        Test.setMock(HttpCalloutMock.class, fakeResponse);

        opportunity = new Opportunity();
        opportunity.Name = 'testOpp';
        opportunity.Amount = 5;
        opportunity.StageName = 'test';
        opportunity.CloseDate = Date.Today();
        insert opportunity;

        contact = new Contact();
        contact.FirstName = 'TestFirst';
        contact.LastName = 'TestLast';
        insert contact;
    }

    @isTest static void testCalculatePaymentSchedulesFuture_DirectDebit() {
        setupConfig();

        Income_Direct_Debit__c dd = new Income_Direct_Debit__c(Opportunity__c = opportunity.Id, DD_Status__c = 'New Instruction', 
                                                                DD_Collection_Period__c = 'Monthly', DD_Start_Date__c = Date.today(),
                                                                DD_Bank_Account_Number__c = '00000000', DD_Bank_Sort_Code__c = '000000');
        insert dd;

        Test.startTest();
        SMP_PaymentScheduleHelper.calculatePaymentSchedulesFuture(new Set<Id>{opportunity.Id});
        Test.stopTest();

        List<Payment_Schedule__c> schedules = [SELECT Id FROM Payment_Schedule__c WHERE Opportunity__c = :opportunity.Id];

        System.assertEquals(12, schedules.Size());
    }

    @isTest static void testCalculatePaymentSchedulesFuture_CardPayment() {
        setupConfig();

        Income_Card_Payment__c cardPayment = new Income_Card_Payment__c(Opportunity__c = opportunity.Id, RP_Enabled__c = true, 
                                                                        RP_Frequency__c = 'Monthly', RP_Start_Date__c = Date.today(), 
                                                                        RP_Collection_Day__c = '1');
        insert cardPayment;

        Test.startTest();
        SMP_PaymentScheduleHelper.calculatePaymentSchedulesFuture(new Set<Id>{opportunity.Id});
        Test.stopTest();

        List<Payment_Schedule__c> schedules = [SELECT Id FROM Payment_Schedule__c WHERE Opportunity__c = :opportunity.Id];

        System.assertEquals(12, schedules.Size());
    }

    @isTest static void testCalculateDirectDebitPaymentSchedules_MonthlyNoEndDate() {
        setupConfig();

        Test.startTest();
        List<Payment_Schedule__c> schedules = SMP_PaymentScheduleHelper.calculateDirectDebitPaymentSchedules(opportunity, new List<npsp__Allocation__c>(), null, Date.today(), null);
        Test.stopTest();

        System.assertEquals(12, schedules.Size());
    }

    @isTest static void testCalculateDirectDebitPaymentSchedules_MonthlyWithEndDate() {
        setupConfig();

        Test.startTest();
        List<Payment_Schedule__c> schedules = SMP_PaymentScheduleHelper.calculateDirectDebitPaymentSchedules(opportunity, new List<npsp__Allocation__c>(), null, Date.today(), Date.today().addMonths(6));
        Test.stopTest();

        if(Date.today().day() > 12){
            System.assertEquals(5, schedules.Size());
        }
        else{
            System.assertEquals(6, schedules.Size());
        }
        
    }

    @isTest static void testCalculateCardPaymentPaymentSchedules_MonthlyNoEndDate() {
        setupConfig();

        Test.startTest();
        List<Payment_Schedule__c> schedules = SMP_PaymentScheduleHelper.calculateCardPaymentSchedules(opportunity, new List<npsp__Allocation__c>(), null, Date.today(), null, '1', 'Monthly');
        Test.stopTest();

        System.assertEquals(12, schedules.Size());
    }

    @isTest static void testCalculateCardPaymentPaymentSchedules_MonthlyWithEndDate() {
        setupConfig();

        Test.startTest();
        List<Payment_Schedule__c> schedules = SMP_PaymentScheduleHelper.calculateCardPaymentSchedules(opportunity, new List<npsp__Allocation__c>(), null, Date.today(), Date.today().addMonths(6), '1', 'Monthly');
        Test.stopTest();

        System.assertEquals(7, schedules.Size());
    }

    @isTest static void testCalculateCardPaymentPaymentSchedules_DailyNoEndDate() {
        setupConfig();

        Test.startTest();
        List<Payment_Schedule__c> schedules = SMP_PaymentScheduleHelper.calculateCardPaymentSchedules(opportunity, new List<npsp__Allocation__c>(), null, Date.today(), null, '1', 'Daily');
        Test.stopTest();

        System.assertEquals(12, schedules.Size());
    }

    @isTest static void testCalculateCardPaymentPaymentSchedules_DailyWithEndDate() {
        setupConfig();

        Test.startTest();
        List<Payment_Schedule__c> schedules = SMP_PaymentScheduleHelper.calculateCardPaymentSchedules(opportunity, new List<npsp__Allocation__c>(), null, Date.today(), Date.today().addDays(2), '1', 'Daily');
        Test.stopTest();

        System.assertEquals(3, schedules.Size());
    }

    @isTest static void testCheckRecurringPayment_WithDD() {
        setupConfig();

        List<Payment_Schedule__c> schedules = new List<Payment_Schedule__c>();
        schedules.add(new Payment_Schedule__c(Opportunity__c = opportunity.Id, Amount__c = 5, Schedule_Date__c = Date.today().addMonths(1), Status__c = 'Outstanding'));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opportunity.Id, Amount__c = 10, Schedule_Date__c = Date.today().addMonths(2), Status__c = 'Outstanding'));
        insert schedules;

        Income_Direct_Debit__c dd = new Income_Direct_Debit__c(Opportunity__c = opportunity.Id, DD_Status__c = 'New Instruction', 
                                                                DD_Collection_Period__c = 'Monthly', DD_Start_Date__c = Date.today(),
                                                                DD_Bank_Account_Number__c = '00000000', DD_Bank_Sort_Code__c = '000000');
        insert dd;

        Test.startTest();
        SMP_PaymentScheduleHelper.checkRecurringPayment(new Set<Id>{opportunity.Id});
        Test.stopTest();

        dd = [SELECT Id, DD_First_Collection_Date__c, DD_First_Collection_Amount__c, DD_Ongoing_Collection_Amount__c, DD_Next_Collection_Date__c, Opportunity__c, DD_Status__c FROM Income_Direct_Debit__c WHERE Id = :dd.Id];
        
        System.assertEquals(schedules[0].Amount__c, dd.DD_First_Collection_Amount__c);
        System.assertEquals(schedules[0].Schedule_Date__c, dd.DD_First_Collection_Date__c);
        System.assertEquals(schedules[0].Amount__c, dd.DD_Ongoing_Collection_Amount__c);
        System.assertEquals(schedules[0].Schedule_Date__c, dd.DD_Next_Collection_Date__c);

        schedules[0].Status__c = 'Paid';
        update schedules;

        dd = SMP_PaymentScheduleHelper.checkDirectDebit(new List<Income_Direct_Debit__c>{dd})[0];

        System.assertEquals(schedules[1].Amount__c, dd.DD_First_Collection_Amount__c);
        System.assertEquals(schedules[1].Schedule_Date__c, dd.DD_First_Collection_Date__c);
        System.assertEquals(schedules[1].Amount__c, dd.DD_Ongoing_Collection_Amount__c);
        System.assertEquals(schedules[1].Schedule_Date__c, dd.DD_Next_Collection_Date__c);
    }

    @isTest static void testCheckRecurringPayment_WithCard() {
        setupConfig();

        List<Payment_Schedule__c> schedules = new List<Payment_Schedule__c>();
        schedules.add(new Payment_Schedule__c(Opportunity__c = opportunity.Id, Amount__c = 5, Schedule_Date__c = Date.today().addMonths(1), Status__c = 'Outstanding'));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opportunity.Id, Amount__c = 10, Schedule_Date__c = Date.today().addMonths(2), Status__c = 'Outstanding'));
        insert schedules;

        Income_Card_Payment__c cardPayment = new Income_Card_Payment__c(Opportunity__c = opportunity.Id, RP_Enabled__c = true, 
                                                                        RP_Frequency__c = 'Monthly', RP_Start_Date__c = Date.today(), 
                                                                        RP_Collection_Day__c = '1');
        insert cardPayment;

        SMP_PaymentScheduleHelper.checkRecurringPayment(new Set<Id>{opportunity.Id});

        cardPayment = [SELECT Id, RP_Amount__c, RP_Next_Payment_Date__c, RP_Enabled__c, Opportunity__c FROM Income_Card_Payment__c WHERE Id = :cardPayment.Id];

        System.assertEquals(schedules[0].Amount__c, cardPayment.RP_Amount__c);
        System.assertEquals(schedules[0].Schedule_Date__c, cardPayment.RP_Next_Payment_Date__c);

        schedules[0].Status__c = 'Paid';
        update schedules;

        cardPayment = SMP_PaymentScheduleHelper.checkRepeatCardPayment(new List<Income_Card_Payment__c>{cardPayment})[0];

        System.assertEquals(schedules[1].Amount__c, cardPayment.RP_Amount__c);
        System.assertEquals(schedules[1].Schedule_Date__c, cardPayment.RP_Next_Payment_Date__c);
    } */
}