objects/Income_Card_Payment__c.object
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Card Payment Details</relationshipLabel>
        <relationshipName>Income_Card_Payment</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Income_Direct_Debit__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Direct Debit Details</relationshipLabel>
        <relationshipName>Income_Direct_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Direct Debit Detail</label>
    <nameField>
        <displayFormat>DD{00000000}</displayFormat>
        <label>AUDDIS Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Debit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Country_Setting__mdt.object
<CustomObject>
    <fields>
        <fullName>Cancel_Url__c</fullName>
        <label>Cancel Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Failed_Url__c</fullName>
        <label>Failed Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Success_Url__c</fullName>
        <label>Success Url</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Country Setting</label>
    <pluralLabel>Payment Country Settings</pluralLabel>
</CustomObject>

classes/CheckoutRouterController.cls
public without sharing class CheckoutRouterController 
{
    public PageReference redirect()
    {
        System.debug('#### CheckoutRouterController.Redirect');

        String websiteCode = '';

        String result = ApexPages.currentpage().getparameters().get('res');
        Id resId = ApexPages.currentpage().getparameters().get('id');

        System.debug('#### result: ' + result);
        System.debug('#### resId: ' + resId);        
                
        try 
        {
            Schema.sObjectType entityType = resId.getSObjectType();  

            if(entityType == Income_Card_Payment__c.sObjectType)
            {
                Income_Card_Payment__c cardPayment = [SELECT Id, Opportunity__c, Opportunity__r.Website_Code__c FROM Income_Card_Payment__c WHERE Id =:resId];
                websiteCode = cardPayment.Opportunity__r.Website_Code__c;
            }
            else if(entityType == Income_Direct_Debit__c.sObjectType)
            {
                Income_Direct_Debit__c directDebit = [SELECT Id, Opportunity__c, Opportunity__r.Website_Code__c FROM Income_Direct_Debit__c WHERE Id =:resId];
                websiteCode = directDebit.Opportunity__r.Website_Code__c;
            }            
        } 
        catch (Exception e) {
            
        }        

        if(String.isBlank(websiteCode))
        {
            websiteCode = 'UK';
        }

        System.debug('#### websiteCode: ' + websiteCode);

        Payment_Country_Setting__mdt setting = [SELECT Success_Url__c, Failed_Url__c, Cancel_Url__c FROM Payment_Country_Setting__mdt WHERE DeveloperName = :websiteCode];
        System.debug('#### setting: ' + setting);

        if(result == 's')
        {
            return new Pagereference(setting.Success_Url__c);
        }
        else if(result == 'f')
        {
            return new Pagereference(setting.Failed_Url__c);
        }
        else if(result == 'c')
        {
            return new Pagereference(setting.Cancel_Url__c);
        }
        else
        {
            return new Pagereference(setting.Failed_Url__c);
        }
    }
}