objects/Income_Direct_Debit__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Income_Direct_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DD_Bank_Account_Number__c</fullName>
        <label>Bank Account Number</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Bank_Sort_Code__c</fullName>
        <label>Bank Sort Code</label>
        <length>6</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_First_Collection_Date__c</fullName>
        <inlineHelpText>This is set by the DD collection engine</inlineHelpText>
        <label>First Collection Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DD_Ongoing_Collection_Amount__c</fullName>
        <label>Ongoing Collection Amount</label>
        <precision>8</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>DD_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Instruction</fullName>
                    <default>true</default>
                    <label>New Instruction</label>
                </value>
                <value>
                    <fullName>First Collection</fullName>
                </value>
                <value>
                    <fullName>Ongoing Collection</fullName>
                </value>
                <value>
                    <fullName>Final Collection</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>First Represent</fullName>
                </value>
                <value>
                    <fullName>Second Represent</fullName>
                </value>
                <value>
                    <fullName>Third Represent</fullName>
                </value>
                <value>
                    <fullName>Cancelled by Payer</fullName>
                </value>
                <value>
                    <fullName>Cancelled by Originator</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Direct Debit Details</relationshipLabel>
        <relationshipName>Income_Direct_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Direct Debit Detail</label>
    <nameField>
        <displayFormat>DD{00000000}</displayFormat>
        <label>AUDDIS Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Debit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Payment_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outstanding</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deprecated Payment Schedule</label>
    <nameField>
        <displayFormat>PSN-{0}</displayFormat>
        <label>Payment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deprecated Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TriggerSettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>Payment_Schedule_Trigger__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Payment Schedule Trigger</label>
        <type>Checkbox</type>
    </fields>
    <label>TriggerSettings</label>
</CustomObject>

classes/TriggerHandler_PaymentScheduleTest.cls
@isTest
public class TriggerHandler_PaymentScheduleTest {
    private static Income_Direct_Debit__c directDebit;
    private static List<Payment_Schedule__c> schedules;

    private static void setupTestConfig(){
        TriggerSettings__c triggersettings = new TriggerSettings__c();
        triggersettings.Payment_Schedule_Trigger__c = true;
        insert triggersettings;

        Contact member = new Contact();
        member.FirstName = 'testFirst';
        member.LastName = 'testLast';
        insert member;

        Opportunity opp = new Opportunity();
        opp.Name = 'testOpp';
        opp.Amount = 5;
        opp.StageName = 'test';
        opp.CloseDate = Date.Today();
        insert opp;

        directDebit = new Income_Direct_Debit__c(Opportunity__c = opp.Id, Contact__c = member.Id, DD_Status__c = 'First Collection', DD_Bank_Account_Number__c = '00000000', DD_Bank_Sort_Code__c = '000000');
        insert directDebit;

        schedules = new List<Payment_Schedule__c>();
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 5, Schedule_Date__c = Date.Today().AddMonths(1).toStartOfMonth()));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 6, Schedule_Date__c = Date.Today().AddMonths(2).toStartOfMonth()));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 7, Schedule_Date__c = Date.Today().AddMonths(3).toStartOfMonth()));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 8, Schedule_Date__c = Date.Today().AddMonths(4).toStartOfMonth()));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 9, Schedule_Date__c = Date.Today().AddMonths(5).toStartOfMonth()));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 10, Schedule_Date__c = Date.Today().AddMonths(6).toStartOfMonth()));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 11, Schedule_Date__c = Date.Today().AddMonths(7).toStartOfMonth()));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 12, Schedule_Date__c = Date.Today().AddMonths(8).toStartOfMonth()));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 13, Schedule_Date__c = Date.Today().AddMonths(9).toStartOfMonth()));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 14, Schedule_Date__c = Date.Today().AddMonths(10).toStartOfMonth()));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 15, Schedule_Date__c = Date.Today().AddMonths(11).toStartOfMonth()));
        schedules.add(new Payment_Schedule__c(Opportunity__c = opp.Id, Status__c = 'Outstanding', Amount__c = 16, Schedule_Date__c = Date.Today().AddMonths(12).toStartOfMonth()));
        insert schedules;
    }

    /* @isTest static void testPaymentScheduleAmountChanged() {
        setupTestConfig();

        directDebit = [SELECT Id, DD_Ongoing_Collection_Amount__c FROM Income_Direct_Debit__c WHERE Id = :directDebit.Id];
        System.assertEquals(5, directDebit.DD_Ongoing_Collection_Amount__c);

        schedules[0].Amount__c = 100;
        update schedules[0];

        directDebit = [SELECT Id, DD_Ongoing_Collection_Amount__c FROM Income_Direct_Debit__c WHERE Id = :directDebit.Id];
        System.assertEquals(100, directDebit.DD_Ongoing_Collection_Amount__c);
    }

    @isTest static void testPaymentScheduleStatusChanged() {
        setupTestConfig();

        directDebit = [SELECT Id, DD_Ongoing_Collection_Amount__c FROM Income_Direct_Debit__c WHERE Id = :directDebit.Id];
        System.assertEquals(5, directDebit.DD_Ongoing_Collection_Amount__c);

        schedules[0].Status__c = 'Paid';
        update schedules[0];

        directDebit = [SELECT Id, DD_Ongoing_Collection_Amount__c FROM Income_Direct_Debit__c WHERE Id = :directDebit.Id];
        System.assertEquals(6, directDebit.DD_Ongoing_Collection_Amount__c);
    }

    @isTest static void testPaymentScheduleDateChanged() {
        setupTestConfig();

        directDebit = [SELECT Id, DD_First_Collection_Date__c FROM Income_Direct_Debit__c WHERE Id = :directDebit.Id];
        System.assertEquals(schedules[0].Schedule_Date__c, directDebit.DD_First_Collection_Date__c);

        schedules[0].Schedule_Date__c = Date.Today().addDays(1);
        update schedules[0];

        directDebit = [SELECT Id, DD_First_Collection_Date__c FROM Income_Direct_Debit__c WHERE Id = :directDebit.Id];
        System.assertEquals(Date.Today().addDays(1), directDebit.DD_First_Collection_Date__c);
    }

    @isTest static void testPaymentScheduleDeleted() {
        setupTestConfig();

        directDebit = [SELECT Id, DD_Ongoing_Collection_Amount__c FROM Income_Direct_Debit__c WHERE Id = :directDebit.Id];
        System.assertEquals(5, directDebit.DD_Ongoing_Collection_Amount__c);

        delete schedules[0];

        directDebit = [SELECT Id, DD_Ongoing_Collection_Amount__c FROM Income_Direct_Debit__c WHERE Id = :directDebit.Id];
        System.assertEquals(6, directDebit.DD_Ongoing_Collection_Amount__c);
    } */
}