objects/Income_Card_Payment__c.object
<CustomObject>
    <description>Smarter Pay - Card Payment Detail</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Income_Card_Payment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gateway_Customer_Reference__c</fullName>
        <label>Gateway Customer Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Card Payment Details</relationshipLabel>
        <relationshipName>Income_Card_Payment</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Payment_Status__c</fullName>
        <label>Payment Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Payment_Vendor__c</fullName>
        <label>Payment Vendor</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Globalpay</fullName>
                </value>
                <value>
                    <fullName>SagePayPi</fullName>
                </value>
                <value>
                    <fullName>Stripe</fullName>
                </value>
                <value>
                    <fullName>SagePay</fullName>
                    <isActive>false</isActive>
                    <label>SagePay</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RP_Amount__c</fullName>
        <label>RP Amount</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>RP_Collection_Day__c</fullName>
        <label>RP Collection Day</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
                <value>
                    <fullName>11</fullName>
                </value>
                <value>
                    <fullName>12</fullName>
                </value>
                <value>
                    <fullName>13</fullName>
                </value>
                <value>
                    <fullName>14</fullName>
                </value>
                <value>
                    <fullName>15</fullName>
                </value>
                <value>
                    <fullName>16</fullName>
                </value>
                <value>
                    <fullName>17</fullName>
                </value>
                <value>
                    <fullName>18</fullName>
                </value>
                <value>
                    <fullName>19</fullName>
                </value>
                <value>
                    <fullName>20</fullName>
                </value>
                <value>
                    <fullName>21</fullName>
                </value>
                <value>
                    <fullName>22</fullName>
                </value>
                <value>
                    <fullName>23</fullName>
                </value>
                <value>
                    <fullName>24</fullName>
                </value>
                <value>
                    <fullName>25</fullName>
                </value>
                <value>
                    <fullName>26</fullName>
                </value>
                <value>
                    <fullName>27</fullName>
                </value>
                <value>
                    <fullName>28</fullName>
                </value>
                <value>
                    <fullName>29</fullName>
                </value>
                <value>
                    <fullName>30</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RP_Description__c</fullName>
        <label>RP Description</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RP_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RP Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RP_Frequency__c</fullName>
        <label>RP Frequency</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Monthly</fullName>
                </value>
                <value>
                    <fullName>Daily</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RP_Next_Payment_Date__c</fullName>
        <label>RP Next Payment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RP_Start_Date__c</fullName>
        <label>RP Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>RP_Stretch__c</fullName>
        <label>RP Stretch</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Sale</fullName>
                </value>
                <value>
                    <fullName>Full Refund</fullName>
                </value>
                <value>
                    <fullName>Partial Refund</fullName>
                </value>
                <value>
                    <fullName>Void</fullName>
                </value>
                <value>
                    <fullName>Deferred</fullName>
                </value>
                <value>
                    <fullName>Deferred_Released</fullName>
                    <label>Deferred Released</label>
                </value>
                <value>
                    <fullName>Deferred_Aborted</fullName>
                    <label>Deferred Aborted</label>
                </value>
                <value>
                    <fullName>Authenticate</fullName>
                </value>
                <value>
                    <fullName>Authorised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Card Payment Detail</label>
    <nameField>
        <displayFormat>HUAPP-{00000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Card Payment Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SmarterPay_Payment_Config__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <fields>
        <fullName>APIKey__c</fullName>
        <label>APIKey</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Manage_Repeat_Payment_Dates__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Manage Repeat Payment Dates</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SmarterPay_User_Name__c</fullName>
        <label>SmarterPay User Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Authenticate_Capture_Ecommerce__c</fullName>
        <label>Standard Authenticate Capture Ecommerce</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Authenticate_Capture_MOTO__c</fullName>
        <label>Standard Authenticate Capture MOTO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Authenticate_Release__c</fullName>
        <label>Standard Authenticate Release</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Deferred_Capture_Ecommerce__c</fullName>
        <label>Standard Deferred Capture Ecommerce</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Deferred_Capture_MOTO__c</fullName>
        <label>Standard Deferred Capture MOTO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Deferred_Release__c</fullName>
        <label>Standard Deferred Release</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Ecommerce__c</fullName>
        <label>Standard Ecommerce</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_MOTO__c</fullName>
        <label>Standard MOTO</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Refund__c</fullName>
        <label>Standard Refund</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Standard_Repeat__c</fullName>
        <label>Standard Repeat</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>SmarterPay Payment Config</label>
</CustomObject>

classes/SMP_RepeatPaymentSchedulerTest.cls
@isTest
public class SMP_RepeatPaymentSchedulerTest {
    
    private static Opportunity opportunity;
    private static Contact contact;

    private static void setupConfig()
    {
        opportunity = new Opportunity();
        opportunity.Name = 'testOpp';
        opportunity.Amount = 5;
        opportunity.StageName = 'test';
        opportunity.CloseDate = Date.Today();
        insert opportunity;

        contact = new Contact();
        contact.FirstName = 'TestFirst';
        contact.LastName = 'TestLast';
        contact.Email = 'test@test.com';
        contact.MailingStreet = 'test';
        contact.MailingCity = 'test';
        contact.MailingPostalCode = 'test';
        contact.MailingState = 'test';  
        contact.MailingCountry = 'UK';
        insert contact;

        SmarterPay_Payment_Config__c paymentConfig = new SmarterPay_Payment_Config__c();
        paymentConfig.APIKey__c = '123456';
        paymentConfig.SmarterPay_User_Name__c = 'test';
        
        paymentConfig.Standard_MOTO__c = '/MOTO';
        paymentConfig.Standard_Ecommerce__c = '/Ecommerce';
        paymentConfig.Standard_Repeat__c = '/Repeat';
        paymentConfig.Standard_Refund__c = '/Refund';
        paymentConfig.Standard_Deferred_Capture_MOTO__c = '/DeferredCaptureMOTO';
        paymentConfig.Standard_Deferred_Capture_Ecommerce__c = '/DeferredCaptureEcommerce';
        paymentConfig.Standard_Deferred_Release__c = '/DeferredRelease'; 
        paymentConfig.Standard_Authenticate_Capture_MOTO__c = '/AuthenticateCaptureMOTO'; 
        paymentConfig.Standard_Authenticate_Capture_Ecommerce__c = '/AuthenticateCaptureEcommerce'; 
        paymentConfig.Standard_Authenticate_Release__c = '/AuthenticateRelease'; 

        paymentConfig.Manage_Repeat_Payment_Dates__c = false;

        insert paymentConfig;
    }  

    @isTest static void testRepeat_ManageNextPaymentDates() {
        setupConfig();

        /* Income_Card_Payment__c cardPayment = new Income_Card_Payment__c(Opportunity__c = opportunity.Id, Contact__c = contact.Id, Transaction_Type__c = 'Sale', Payment_Vendor__c = 'Stripe', 
                                                                        Transaction_ID__c = '1234', Gateway_Customer_Reference__c = '1234', Payment_Status__c = 'Successful',
                                                                        RP_Stretch__c = '1', RP_Collection_Day__c = '1', RP_Start_Date__c = Date.Today(), RP_Next_Payment_Date__c = Date.Today(),
                                                                        RP_Frequency__c = 'Daily', RP_Enabled__c = true, RP_Description__c = 'test', RP_Amount__c = 5);
        insert cardPayment;

        String responseBody = '{"response":[{"status":"success","message":""}]}';        
        HttpRestCallOutMock fakeResponse = new HttpRestCallOutMock(200, responseBody);
        Test.setMock(HttpCalloutMock.class, fakeResponse); */
        
        Test.StartTest();
        SMP_RepeatPaymentScheduler sched = new SMP_RepeatPaymentScheduler();
        sched.execute(null);
        Test.StopTest();        
    }
}