objects/Income_Debit_History__c.object
<CustomObject>
    <fields>
        <fullName>DD_Code__c</fullName>
        <label>DD Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DD_Stage__c</fullName>
        <label>DD Stage</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Submitted</fullName>
                    <default>true</default>
                    <label>Submitted</label>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
                <value>
                    <fullName>Successful</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DD_Status__c</fullName>
        <label>DD Status</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Income_Direct_Debit__c</fullName>
        <label>Income Direct Debit</label>
        <referenceTo>Income_Direct_Debit__c</referenceTo>
        <relationshipLabel>Income Debit History</relationshipLabel>
        <relationshipName>Income_Debit_History</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Income Debit History</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Income Debit History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income Debit History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Income_Direct_Debit__c.object
<CustomObject>
    <fields>
        <fullName>DD_Account_Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>DD_Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New Instruction</fullName>
                    <default>true</default>
                    <label>New Instruction</label>
                </value>
                <value>
                    <fullName>First Collection</fullName>
                </value>
                <value>
                    <fullName>Ongoing Collection</fullName>
                </value>
                <value>
                    <fullName>Final Collection</fullName>
                </value>
                <value>
                    <fullName>On Hold</fullName>
                </value>
                <value>
                    <fullName>Expired</fullName>
                </value>
                <value>
                    <fullName>First Represent</fullName>
                </value>
                <value>
                    <fullName>Second Represent</fullName>
                </value>
                <value>
                    <fullName>Third Represent</fullName>
                </value>
                <value>
                    <fullName>Cancelled by Payer</fullName>
                </value>
                <value>
                    <fullName>Cancelled by Originator</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Direct Debit Details</relationshipLabel>
        <relationshipName>Income_Direct_Debit</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Direct Debit Detail</label>
    <nameField>
        <displayFormat>DD{00000000}</displayFormat>
        <label>AUDDIS Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Direct Debit Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SMP_DirectDebitHelper.cls
public with sharing class SMP_DirectDebitHelper{
    public static Map<Id, Income_Direct_Debit__c> getParentDirectDebitsFromHistories(List<Income_Debit_History__c> historiesMap){
        System.debug('#### getParentDirectDebitsFromHistories');

        Set<Id> directDebitIds = new Set<Id>();

        for(Income_Debit_History__c history : historiesMap){
            directDebitIds.add(history.Income_Direct_Debit__c);
        }

        Map<Id, Income_Direct_Debit__c> directDebits = new Map<Id, Income_Direct_Debit__c>([SELECT Id, Opportunity__c, DD_Account_Email__c 
                                                                                            FROM Income_Direct_Debit__c
                                                                                            WHERE Id IN :directDebitIds]);

        return directDebits;
    }

    public static List<Income_Debit_History__c> getNewInstructions(List<Income_Debit_History__c> histories){
        System.debug('#### getNewInstructions');
        System.debug('#### histories: '+histories);

        List<Income_Debit_History__c> newInstructionsList = new List<Income_Debit_History__c>();

        for(Income_Debit_History__c history : histories){
            if(history.DD_Status__c == 'New Instruction'){
                newInstructionsList.add(history);
            }
        }

        return newInstructionsList;
    }

    public static List<Income_Debit_History__c> getNewInstructionsByStage(List<Income_Debit_History__c> newDDHistories, Map<Id, Income_Debit_History__c> oldDDHistories, String stage)
    {
        System.debug('#### getNewInstructionsByStage');
        System.debug('#### newDDHistories: ' + newDDHistories);
        System.debug('#### oldDDHistories: ' + oldDDHistories);
        System.debug('#### stage: ' + stage);

        List<Income_Debit_History__c> newInstructionsList = new List<Income_Debit_History__c>();

        for(Income_Debit_History__c history : newDDHistories)
        {
            if(history.DD_Status__c == 'New Instruction')
            {
                if(history.DD_Stage__c == stage && (oldDDHistories == null || oldDDHistories.get(history.Id) == null || oldDDHistories.get(history.Id).DD_Stage__c != stage))
                {
                    newInstructionsList.add(history);
                }               
            }
        }

        return newInstructionsList;
    }

    public static List<Income_Debit_History__c> getCollections(List<Income_Debit_History__c> histories)
    {
        System.debug('#### getCollections');
        System.debug('#### histories: '+histories);

        List<Income_Debit_History__c> collectionsList = new List<Income_Debit_History__c>();

        for(Income_Debit_History__c history : histories)
        {
            if(history.DD_Status__c == 'First Collection' || history.DD_Status__c == 'Ongoing Collection' || history.DD_Status__c == 'Final Collection'
                || history.DD_Status__c == 'First Represent' || history.DD_Status__c == 'Second Represent' || history.DD_Status__c == 'Third Represent')
            {
                collectionsList.add(history);
            }
        }

        return collectionsList;
    }

    public static List<Income_Debit_History__c> getCollectionsByStage(List<Income_Debit_History__c> newDDHistories, Map<Id, Income_Debit_History__c> oldDDHistories, String stage)
    {
        System.debug('#### getCollectionsByStage');
        System.debug('#### newDDHistories: ' + newDDHistories);
        System.debug('#### oldDDHistories: ' + oldDDHistories);
        System.debug('#### stage: ' + stage);
        
        List<Income_Debit_History__c> collections = new List<Income_Debit_History__c>();

        for(Income_Debit_History__c history : newDDHistories)
        {
            if(history.DD_Status__c == 'First Collection' || history.DD_Status__c == 'Ongoing Collection' || history.DD_Status__c == 'Final Collection'
                || history.DD_Status__c == 'First Represent' || history.DD_Status__c == 'Second Represent' || history.DD_Status__c == 'Third Represent')
            {
                if(history.DD_Stage__c == stage && (oldDDHistories == null || oldDDHistories.get(history.Id) == null || oldDDHistories.get(history.Id).DD_Stage__c != stage))
                {
                    collections.add(history);
                }               
            }
        }

        return collections;
    }

    public static List<Income_Debit_History__c> getHistoriesByStatus(List<Income_Debit_History__c> histories, Map<Id, Income_Debit_History__c> oldDDHistories, String status)
    {
        System.debug('#### getHistoriesByStatus');
        System.debug('#### histories: ' + histories);
        System.debug('#### oldDDHistories: ' + oldDDHistories);
        System.debug('#### status: ' + status);

        List<Income_Debit_History__c> collectionsList = new List<Income_Debit_History__c>();

        for(Income_Debit_History__c history : histories)
        {
            if(String.isNotBlank(history.DD_Status__c) && history.DD_Status__c.contains(status) && (oldDDHistories == null || oldDDHistories.get(history.Id) == null || history.DD_Status__c != oldDDHistories.get(history.Id).DD_Status__c))
            {
                collectionsList.add(history);
            }
        }

        System.debug('#### Returning: ' + collectionsList);
        return collectionsList;
    }

    public static List<Income_Debit_History__c> getHistoriesByReasonCode(List<Income_Debit_History__c> histories, Map<Id, Income_Debit_History__c> oldDDHistories, Set<String> reasonCodes)
    {
        System.debug('#### getHistoriesByReasonCode');
        System.debug('#### histories: ' + histories);
        System.debug('#### oldDDHistories: ' + oldDDHistories);
        System.debug('#### reasonCodes: ' + reasonCodes);

        List<Income_Debit_History__c> collectionsList = new List<Income_Debit_History__c>();

        for(Income_Debit_History__c history : histories)
        {
            for (String reasonCode : reasonCodes) 
            {     
                if(String.isNotBlank(history.DD_Code__c) && history.DD_Code__c.contains(reasonCode) 
                    && (oldDDHistories == null || oldDDHistories.get(history.Id) == null || history.DD_Code__c != oldDDHistories.get(history.Id).DD_Code__c))
                {
                    collectionsList.add(history);
                }
            }
        }

        return collectionsList;
    }
}