objects/Orphan_Visit__c.object
<CustomObject>
    <description>Orphan Visit For Field Office</description>
    <fields>
        <fullName>Comments__c</fullName>
        <label>Comments</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Orphan__c</fullName>
        <label>Orphan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Orphan</value>
            </filterItems>
            <infoMessage>Please select an Orphan</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orphan Visits</relationshipLabel>
        <relationshipName>Orphan_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Orphan Visit</label>
    <nameField>
        <displayFormat>VISIT-{00000}</displayFormat>
        <label>Orphan Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orphan Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LaunchOrphanVisitForm_Test.cls
@isTest
public class LaunchOrphanVisitForm_Test {
        
    @isTest static void testfetchOrphanVisitsWithOrphan() {
        Date dueDate = Date.today();
        List<Orphan_Visit__c> listOrphanVisits = new List<Orphan_Visit__c>();
        Integer countVisits;
        test.startTest();
        Contact orphanContact = (Contact) TestFactory.createSObject(
            new Contact(LastName='test',RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Orphan').getRecordTypeId()),
            true
        );
        Orphan_Visit__c orphanVisit = (Orphan_Visit__c)TestFactory.createSObject(
            new Orphan_Visit__c(Orphan__c=orphanContact.Id,Comments__c='test',Status__c='In Progress',Due_Date__c=dueDate),
            true
        );
        listOrphanVisits = LaunchOrphanVisitForm.fetchOrphanVisits(orphanContact.Id);
        listOrphanVisits = LaunchOrphanVisitForm.fetchOrphanVisitsbySearch('test', orphanContact.Id);
        countVisits = LaunchOrphanVisitForm.countOrphanVisitsbySearch('test', orphanContact.Id);
        test.stopTest();
    }
    
    @isTest static void testfetchOrphanVisitsWithoutOrphan() {
        Date dueDate = Date.today();
        List<Orphan_Visit__c> listOrphanVisits = new List<Orphan_Visit__c>();
        Integer countVisits;
        test.startTest();
        Contact orphanContact = (Contact) TestFactory.createSObject(
            new Contact(RecordTypeId=Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Orphan').getRecordTypeId()),
            true
        );
        Orphan_Visit__c orphanVisit = (Orphan_Visit__c)TestFactory.createSObject(
            new Orphan_Visit__c(Orphan__c=orphanContact.Id,Comments__c='test',Status__c='In Progress',Due_Date__c=dueDate),
            true
        );
        listOrphanVisits = LaunchOrphanVisitForm.fetchOrphanVisits(null);
        listOrphanVisits = LaunchOrphanVisitForm.fetchOrphanVisitsbySearch('test', null);
        countVisits = LaunchOrphanVisitForm.countOrphanVisitsbySearch(null, null);
        test.stopTest();
    }
}