objects/Orphan_Visit__c.object
<CustomObject>
    <description>Orphan Visit For Field Office</description>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Orphan_Visit_Form__c</fullName>
        <formula>IF( ISPICKVAL( Status__c , &quot;Completed&quot;),&quot;Orphan Visit form already completed&quot;, HYPERLINK(&quot;/flow/Orphan_Visit_Form_on_Visit?recordId=&quot;+ CASESAFEID(Id) , &quot;Orphan Visit&quot;, &quot;_self&quot;))</formula>
        <label>Orphan Visit Form</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Orphan__c</fullName>
        <label>Orphan</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Orphan</value>
            </filterItems>
            <infoMessage>Please select an Orphan</infoMessage>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orphan Visits</relationshipLabel>
        <relationshipName>Orphan_Visits</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>In Progress</fullName>
                </value>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Orphan Visit</label>
    <nameField>
        <displayFormat>VISIT-{00000}</displayFormat>
        <label>Orphan Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orphan Visits</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LaunchOrphanVisitForm.cls
public with sharing class LaunchOrphanVisitForm{
    @AuraEnabled
    public static List <Orphan_Visit__c> fetchOrphanVisits(String OrphanId) {
        List<Orphan_Visit__c> listOrphanVisits = new List<Orphan_Visit__c>();
        if(String.isEmpty(OrphanId)){
        listOrphanVisits = [SELECT Id,Orphan__c, Orphan__r.Sponsoree_ID__c,Orphan__r.Name,
                            Status__c, Due_Date__c, Orphan_Visit_Form__c FROM Orphan_Visit__c
                           	where Status__c='In Progress' AND (Due_Date__c = THIS_YEAR OR Due_Date__c = LAST_YEAR ) ORDER By Due_Date__c ASC limit 10 ];
        }else{
            listOrphanVisits = [SELECT Id,Orphan__c, Orphan__r.Sponsoree_ID__c,Orphan__r.Name,
                                Status__c, Due_Date__c, Orphan_Visit_Form__c FROM Orphan_Visit__c
                                where Status__c='In Progress' AND (Due_Date__c = THIS_YEAR OR Due_Date__c = LAST_YEAR ) AND Orphan__c = :OrphanId ORDER By Due_Date__c ASC limit 10 ];
        }
        return listOrphanVisits;
    }
    @AuraEnabled
    public static List <Orphan_Visit__c> fetchOrphanVisitsbySearch(String key, String OrphanId) {
        String searchKey = '%'+key+'%';
        List<Orphan_Visit__c> listOrphanVisits = new List<Orphan_Visit__c>();
        listOrphanVisits = [SELECT Id,Orphan__c, Orphan__r.Sponsoree_ID__c,Orphan__r.Name,
                            Status__c, Due_Date__c, Orphan_Visit_Form__c FROM Orphan_Visit__c
                           	where Status__c='In Progress' AND (Due_Date__c = THIS_YEAR OR Due_Date__c = LAST_YEAR ) AND//AND Orphan__c=:OrphanId 
                            (Orphan__r.Name like :searchKey OR Orphan__r.Sponsoree_ID__c like:searchKey OR Orphan__r.MailingCity like:searchKey
                            OR Orphan__r.MailingCountry like:searchKey OR Orphan__r.MailingStreet like:searchKey OR Orphan__r.MailingState like: searchKey) ORDER By Due_Date__c ASC limit 10];
        return listOrphanVisits;
    }
    @AuraEnabled
    public static Integer countOrphanVisitsbySearch(String key,String OrphanId) {
        String searchKey = '%'+key+'%';
        List<Orphan_Visit__c> listOrphanVisits = new List<Orphan_Visit__c>();
        if(key!=null && !String.isBlank(key) && !String.isEmpty(key) && key!=''){
            listOrphanVisits = [SELECT Id,Orphan__c, Orphan__r.Sponsoree_ID__c,Orphan__r.Name,
                                Status__c, Due_Date__c, Orphan_Visit_Form__c FROM Orphan_Visit__c
                                where Status__c='In Progress' AND (Due_Date__c = THIS_YEAR OR Due_Date__c = LAST_YEAR ) AND
                                (Orphan__r.Name like :searchKey OR Orphan__r.Sponsoree_ID__c like:searchKey OR Orphan__r.MailingCity like:searchKey
                                OR Orphan__r.MailingCountry like:searchKey OR Orphan__r.MailingStreet like:searchKey OR Orphan__r.MailingState like: searchKey) ORDER By Due_Date__c ASC ];//AND Orphan__c=:OrphanId
            return listOrphanVisits.size();
        }else{
            listOrphanVisits = [SELECT Id,Orphan__c, Orphan__r.Sponsoree_ID__c,Orphan__r.Name,
                            	Status__c, Due_Date__c, Orphan_Visit_Form__c FROM Orphan_Visit__c
                           		where Status__c='In Progress' AND (Due_Date__c = THIS_YEAR OR Due_Date__c = LAST_YEAR ) ORDER By Due_Date__c ASC];//AND Orphan__c=:OrphanId
        	
            return listOrphanVisits.size();
        }
        
    }
}