objects/Payment_Schedule__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Payment_Schedules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Schedule_Date__c</fullName>
        <label>Schedule Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Outstanding</fullName>
                </value>
                <value>
                    <fullName>Paid</fullName>
                </value>
                <value>
                    <fullName>Failed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Deprecated Payment Schedule</label>
    <nameField>
        <displayFormat>PSN-{0}</displayFormat>
        <label>Payment Schedule Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Deprecated Payment Schedules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TriggerHandler_PaymentSchedule.cls
public without sharing class TriggerHandler_PaymentSchedule {

    public static void OnBeforeInsert(List<Payment_Schedule__c> newRecords)
    {        
    }

    public static void OnAfterInsert(Map<Id, Payment_Schedule__c> newRecords)
    {
        /* Set<Id> contactsToCheck = new Set<Id>();

        for(Payment_Schedule__c ps : newRecords.values())
        {
            contactsToCheck.add(ps.Opportunity__c);
        }
        
        SMP_PaymentScheduleHelper.checkRecurringPayment(contactsToCheck); */
    }

    public static void OnBeforeUpdate(Map<Id, Payment_Schedule__c> newRecords, Map<Id, Payment_Schedule__c> oldRecords)
    {
        System.debug('#### newRecords: ' + newRecords);
        System.debug('#### oldRecords: ' + oldRecords);
    }
    
    public static void OnAfterUpdate(Map<Id, Payment_Schedule__c> newRecords, Map<Id, Payment_Schedule__c> oldRecords)
    {
        System.debug('TriggerHandler_PaymentSchedule OnAfterUpdate');
        System.debug('#### newRecords: ' + newRecords);
        System.debug('#### oldRecords: ' + oldRecords);

        /* Set<Id> opportunitiesToRecalculate = new Set<Id>();
        Set<Id> recurringPaymentsToRecalculate = new Set<Id>();

        for(Payment_Schedule__c ps : newRecords.values())
        {            
            if(ps.Status__c != oldRecords.get(ps.Id).Status__c)
            {
                opportunitiesToRecalculate.add(ps.Opportunity__c);
                recurringPaymentsToRecalculate.add(ps.Opportunity__c);
            }

            if(ps.Amount__c != oldRecords.get(ps.Id).Amount__c
            || ps.Schedule_Date__c != oldRecords.get(ps.Id).Schedule_Date__c)
            {
                recurringPaymentsToRecalculate.add(ps.Opportunity__c);
            }
        }
        
        if(opportunitiesToRecalculate.Size() > 0)
        {
            SMP_PaymentScheduleHelper.calculatePaymentSchedulesFuture(opportunitiesToRecalculate);
        }        
        
        if(recurringPaymentsToRecalculate.Size () > 0)
        {
            SMP_PaymentScheduleHelper.checkRecurringPayment(recurringPaymentsToRecalculate);
        }         */
    }

    public static void OnAfterDelete(Map<Id, Payment_Schedule__c> oldRecords)
    {
        System.debug('TriggerHandler_PaymentSchedule OnAfterDelete');
        System.debug('#### oldRecords: ' + oldRecords);

        /* Set<Id> recurringPaymentsToRecalculate = new Set<Id>();

        for(Payment_Schedule__c ps : oldRecords.values())
        {       
            recurringPaymentsToRecalculate.add(ps.Opportunity__c);
        }    
        
        SMP_PaymentScheduleHelper.checkRecurringPayment(recurringPaymentsToRecalculate); */       
    }
}