objects/Payment_Event__e.object
<CustomObject>
    <description>Payment Event</description>
    <fields>
        <fullName>Internal_Payment_Description__c</fullName>
        <description>Internal Payment Description</description>
        <label>Internal Payment Description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payment Event</label>
    <pluralLabel>Payment Event</pluralLabel>
</CustomObject>

classes/PaymentEventTriggerHandlerTest.cls
/**
 * @description       :
 * @author            : agentgill
 * @group             :
 * @last modified on  : 07-11-2020
 * @last modified by  : agentgill
 * Modifications Log
 * Ver   Date         Author      Modification
 * 1.0   07-05-2020   agentgill   Initial Version
 **/
@isTest
public with sharing class PaymentEventTriggerHandlerTest {
    @isTest
    private static void testPublishPaymentEvent() {
        Test.startTest();
        Payment_Event__e event = new Payment_Event__e(
            Internal_Payment_Description__c = 'TestME'
        );
        EventBus.publish(event);
        Test.stopTest();
        System.assertEquals(
            1,
            PaymentEventTriggerHandler.unknownEvents.size(),
            'Something not right'
        );
    }
}