objects/Recurring_Donation_Batch_Errors__c.object
<CustomObject>
    <description>Error Logs</description>
    <fields>
        <fullName>Error_Context__c</fullName>
        <label>Error Context</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EventDetails__c</fullName>
        <label>Error Details</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object__c</fullName>
        <label>Object</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>RD-{DD}-{MM}-{0000}</displayFormat>
        <label>ERROR #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HA_Logger.cls
/**
 * @description       : 
 * @author            : Iamsfdeveloper
 * @group             : 
 * @last modified on  : 02-08-2021
 * @last modified by  : Iamsfdeveloper
 * Modifications Log 
 * Ver   Date         Author           Modification
 * 1.0   02-08-2021   Iamsfdeveloper   Initial Version
**/
public with sharing class HA_Logger {
    public static void CreateErrorLog(String ErrorDetails,String ObjectName,String ErrorContext){
        insert new Recurring_Donation_Batch_Errors__c(EventDetails__c =ErrorDetails,Object__c=ObjectName,Error_Context__c=ErrorContext);
    }
}